/* Build the Riemann–Roch laboratory into one self-contained page.
 *
 * Inputs:  src/template.html (markup, with @@STYLE@@, @@BEAMDSWITCH@@, @@ENGINE@@ and @@UI@@ markers),
 *          src/style.css, src/engine.js (the pure engine), src/ui.js (the page), beamdswitch.js (the
 *          site's report template, a verbatim copy of templates/beamdswitch.js).
 * Outputs: index.html (everything inlined; works offline from file://) and raw.json (catalogue data
 *          computed by the engine: presets, the minimum computations, references).
 *
 *   node build.mjs          write both outputs
 *   node build.mjs --check  exit 1 if either output is stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const HERE = dirname(fileURLToPath(import.meta.url));
const read = (/** @type {string} */ p) => readFileSync(join(HERE, p), "utf8");

export function render() {
  /** @type {Record<string, string>} */
  const parts = { STYLE: read("src/style.css"), BEAMDSWITCH: read("beamdswitch.js"), ENGINE: read("src/engine.js"), UI: read("src/ui.js") };
  for (const [k, v] of Object.entries(parts)) if (/<\/(script|style)/i.test(v)) throw new Error(`${k} must not contain a closing script or style tag`);
  const html = read("src/template.html").replace(/@@(STYLE|BEAMDSWITCH|ENGINE|UI)@@/g, (_, k) => parts[k]);
  /** @type {{ self?: unknown, RiemannRoch?: typeof RiemannRoch }} */
  const ctx = {}; ctx.self = ctx;
  vm.runInNewContext(parts.ENGINE, ctx);
  const RR = /** @type {typeof RiemannRoch} the engine sets it */ (ctx.RiemannRoch);
  const raw = {
    title: "Divisors, Linear Systems & Riemann–Roch Laboratory",
    url: "https://teoyujie.org/visuals/riemann-roch",
    note: "Catalogue data, generated by build.mjs from the engine. The page never fetches this file.",
    curves: Object.fromEntries(Object.entries(RR.CURVES).map(([k, v]) => [k, v.label])),
    symbolic_cases: ["P¹: L(D) = { r·xⁱ/q : 0 ≤ i ≤ deg D } for any divisor", "Weierstrass E at O: xⁱyʲ, j ≤ 1, 2i + 3j ≤ n", "y² = f(x), deg f = 2g + 1, at ∞: xⁱ (pole 2i) and y·xʲ (pole 2j + 2g + 1)", "y² = f(x), deg f = 2g + 2: n(∞₊ + ∞₋)", "smooth plane curve of degree d: ℓ(nH) = C(n+2, 2) − C(n−d+2, 2)"],
    presets: RR.PRESETS.map((p) => ({ id: p.id, title: p.title })),
    minimum_computations: JSON.parse(JSON.stringify(RR.minimumComputations())),
    references: JSON.parse(JSON.stringify(RR.REFERENCES)),
  };
  return { "index.html": html, "raw.json": JSON.stringify(raw, null, 2) + "\n" };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const out = render(), check = process.argv.includes("--check");
  let stale = false;
  for (const [name, text] of Object.entries(out)) {
    let cur = null; try { cur = read(name); } catch { /* missing */ }
    if (cur === text) continue;
    if (check) { console.error(`${name} is stale: run node build.mjs`); stale = true; }
    else { writeFileSync(join(HERE, name), text); console.log(`wrote ${name}`); }
  }
  if (stale) process.exit(1);
}
