#!/usr/bin/env python3
"""Build index.html from src/, report.js, raw.json and the shared kit: scripts/visual_build.py says how.

    python3 build.py            # write index.html
    python3 build.py --verify   # check index.html is current without writing it

Generated by scripts/new_visual.py; --update rewrites this file.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1] / "scripts"))

from visual_build import main  # noqa: E402

if __name__ == "__main__":
    main(HERE)
