/* Étale Fundamental Group — the pure engine (self.Etale).
 *
 * Everything the page draws is computed here first: permutations of fibres, monodromy obtained by
 * lifting loops numerically through explicit covers, finite fields and Frobenius orbits,
 * Artin–Schreier extensions, Hasse invariants and point counts, surface-group presentations and
 * 4g-gon gluings, torsion of complex tori, cyclotomic Galois actions and the beamdswitch report.
 * No DOM, storage, clock, randomness or network.
 *
 * Conventions. Points of a fibre are 0..n−1 internally and 1..n on screen. A permutation is an
 * array p with p[i] the image of i. Loops act on fibres on the right and paths compose left to
 * right, so the loop γδ (γ first) acts by compose(γ, δ), where compose(p, q)[i] = q[p[i]].
 */
(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.Etale = api;
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  /* ---------------- permutations ---------------- */
  const identity = (n) => Array.from({ length: n }, (_, i) => i);
  const compose = (...ps) => ps.reduce((acc, p) => acc.map((i) => p[i]));
  const inverse = (p) => { const q = new Array(p.length); p.forEach((v, i) => { q[v] = i; }); return q; };
  const equal = (p, q) => p.length === q.length && p.every((v, i) => v === q[i]);
  const power = (p, k) => {
    let r = identity(p.length), b = k < 0 ? inverse(p) : p.slice();
    for (let e = Math.abs(k); e > 0; e >>= 1) { if (e & 1) r = compose(r, b); b = compose(b, b); }
    return r;
  };
  function cycles(p, withFixed = false) {
    const seen = new Array(p.length).fill(false), out = [];
    for (let i = 0; i < p.length; i++) {
      if (seen[i]) continue;
      const c = [];
      for (let j = i; !seen[j]; j = p[j]) { seen[j] = true; c.push(j); }
      if (c.length > 1 || withFixed) out.push(c);
    }
    return out;
  }
  const gcd = (a, b) => { a = Math.abs(a); b = Math.abs(b); while (b) [a, b] = [b, a % b]; return a; };
  const lcm = (a, b) => (a / gcd(a, b)) * b;
  const order = (p) => cycles(p).reduce((m, c) => lcm(m, c.length), 1);
  const cycleType = (p) => cycles(p, true).map((c) => c.length).sort((a, b) => b - a);
  /* Cycle notation, 1-based: "(1 2 3)(4 5)", or "id". */
  const cycleString = (p, labels) => {
    const cs = cycles(p);
    if (!cs.length) return "id";
    const name = labels ? (i) => labels[i] : (i) => String(i + 1);
    return cs.map((c) => `(${c.map(name).join(" ")})`).join("");
  };
  /* Parse "(1 2)(3 4 5)" on n points. */
  function parseCycles(s, n) {
    const p = identity(n);
    for (const m of String(s).matchAll(/\(([^)]*)\)/g)) {
      const c = m[1].trim().split(/[\s,]+/).filter(Boolean).map((x) => Number(x) - 1);
      if (c.some((x) => !Number.isInteger(x) || x < 0 || x >= n)) throw new Error(`Bad cycle ${m[0]} on ${n} points.`);
      c.forEach((x, i) => { p[x] = c[(i + 1) % c.length]; });
    }
    if (new Set(p).size !== n) throw new Error(`"${s}" is not a permutation.`);
    return p;
  }
  /* Orbits of the group generated by gens on 0..n−1. */
  function orbits(gens, n) {
    const seen = new Array(n).fill(false), out = [];
    for (let s = 0; s < n; s++) {
      if (seen[s]) continue;
      const orb = [s]; seen[s] = true;
      for (let k = 0; k < orb.length; k++) for (const g of gens) for (const h of [g, inverse(g)]) {
        const j = h[orb[k]];
        if (!seen[j]) { seen[j] = true; orb.push(j); }
      }
      out.push(orb.sort((a, b) => a - b));
    }
    return out;
  }
  const isTransitive = (gens, n) => orbits(gens, n).length === 1;
  /* The finite group generated by gens (as permutations), by closure; capped for safety. */
  function generate(gens, n, cap = 5040) {
    const key = (p) => p.join(","), start = identity(n), seen = new Map([[key(start), start]]), queue = [start];
    while (queue.length) {
      const g = queue.shift();
      for (const h of gens) {
        const k = compose(g, h), s = key(k);
        if (!seen.has(s)) { seen.set(s, k); queue.push(k); if (seen.size > cap) throw new Error("Group too large to enumerate."); }
      }
    }
    return [...seen.values()];
  }
  /* Permutations of the fibre commuting with every generator: the deck (automorphism) group of the cover. */
  function centralizer(gens, n) {
    if (!gens.length) return generate([], n);
    // A deck transformation is determined by where it sends point 0 (for a transitive action).
    const out = [];
    if (!isTransitive(gens, n)) throw new Error("centralizer expects a connected cover (transitive monodromy).");
    for (let t = 0; t < n; t++) {
      const f = new Array(n).fill(-1); f[0] = t;
      const stack = [0]; let ok = true;
      while (stack.length && ok) {
        const i = stack.pop();
        for (const g of gens) for (const h of [g, inverse(g)]) {
          const j = h[i], fj = h[f[i]];
          if (f[j] === -1) { f[j] = fj; stack.push(j); } else if (f[j] !== fj) { ok = false; break; }
        }
      }
      if (ok && new Set(f).size === n && gens.every((g) => equal(compose(g, f), compose(f, g)))) out.push(f);
    }
    return out;
  }

  /* ---------------- complex numbers ---------------- */
  const C = (re, im = 0) => ({ re, im });
  const cadd = (a, b) => C(a.re + b.re, a.im + b.im);
  const csub = (a, b) => C(a.re - b.re, a.im - b.im);
  const cmul = (a, b) => C(a.re * b.re - a.im * b.im, a.re * b.im + a.im * b.re);
  const cdiv = (a, b) => { const d = b.re * b.re + b.im * b.im; return C((a.re * b.re + a.im * b.im) / d, (a.im * b.re - a.re * b.im) / d); };
  const cabs = (a) => Math.hypot(a.re, a.im);
  const cexpi = (t) => C(Math.cos(t), Math.sin(t));
  const cscale = (a, s) => C(a.re * s, a.im * s);
  /* Evaluate a polynomial with complex coefficients (low degree first) and its derivative. */
  function cpoly(coeffs, z) {
    let p = C(0), d = C(0);
    for (let k = coeffs.length - 1; k >= 0; k--) { d = cadd(cmul(d, z), p); p = cadd(cmul(p, z), coeffs[k]); }
    return { p, d };
  }
  /* All roots of a polynomial (Durand–Kerner), coefficients low degree first, complex. */
  function croots(coeffs) {
    const n = coeffs.length - 1, lead = coeffs[n], mon = coeffs.map((c) => cdiv(c, lead));
    let z = Array.from({ length: n }, (_, k) => { let w = C(1); const b = C(0.4, 0.9); for (let j = 0; j < k; j++) w = cmul(w, b); return w; });
    for (let it = 0; it < 500; it++) {
      let delta = 0;
      z = z.map((zi, i) => {
        let den = C(1);
        z.forEach((zj, j) => { if (j !== i) den = cmul(den, csub(zi, zj)); });
        const step = cdiv(cpoly(mon, zi).p, den);
        delta = Math.max(delta, cabs(step));
        return csub(zi, step);
      });
      if (delta < 1e-14) break;
    }
    return z;
  }

  /* ---------------- lifting loops through covers ----------------
   * A cover is given by its fibre polynomial: over a base point t the fibre is the set of roots x
   * of F(x, t) = 0. A path in the base is lifted by Newton continuation from each starting root;
   * the monodromy is where each starting point ends up. Steps refine automatically, and a lift that
   * would jump onto another lift's track (a step too close to a branch point) is refused. */
  function liftPath(cover, path, start) {
    const F = (x, t) => cpoly(cover.coeffs(t), x);
    let xs = start ? start.slice() : cover.fibre(path[0]);
    const tracks = xs.map((x) => [x]);
    for (let k = 1; k < path.length; k++) {
      const subs = 4;
      for (let s = 1; s <= subs; s++) {
        const t = cadd(path[k - 1], cscale(csub(path[k], path[k - 1]), s / subs));
        xs = xs.map((x) => {
          let y = x;
          for (let it = 0; it < 40; it++) {
            const { p, d } = F(y, t), step = cdiv(p, d);
            y = csub(y, step);
            if (cabs(step) < 1e-13) break;
          }
          return y;
        });
      }
      let minGap = Infinity;
      for (let i = 0; i < xs.length; i++) for (let j = i + 1; j < xs.length; j++) minGap = Math.min(minGap, cabs(csub(xs[i], xs[j])));
      if (minGap < 1e-6) throw new Error("Two lifts met: the path passes through a branch point.");
      xs.forEach((x, i) => tracks[i].push(x));
    }
    return { tracks, end: xs };
  }
  /* Monodromy of a closed loop: point i of the fibre ends at point perm[i]. */
  function monodromy(cover, path) {
    const fib = cover.fibre(path[0]), { tracks, end } = liftPath(cover, path, fib);
    const perm = end.map((x) => {
      let best = -1, bd = Infinity;
      fib.forEach((y, j) => { const d = cabs(csub(x, y)); if (d < bd) { bd = d; best = j; } });
      if (bd > 1e-7) throw new Error("A lift did not close up on the fibre.");
      return best;
    });
    if (new Set(perm).size !== perm.length) throw new Error("Monodromy is not a permutation.");
    return { perm, tracks, fibre: fib };
  }
  /* Loops in the base. circleLoop: centre c, radius r, starting angle a0, turning dir times round
   * (counterclockwise for dir > 0). */
  const circleLoop = (c, r, a0 = 0, steps = 720, dir = 1) =>
    Array.from({ length: steps + 1 }, (_, k) => cadd(c, cscale(cexpi(a0 + (dir * 2 * Math.PI * k) / steps), r)));
  /* A lasso: from base point b straight to the circle of radius r about c, once round it, and back. */
  function lassoLoop(b, c, r, dir = 1, steps = 720) {
    const v = csub(b, c), a0 = Math.atan2(v.im, v.re), p0 = cadd(c, cscale(cexpi(a0), r));
    const seg = (A, B, m) => Array.from({ length: m + 1 }, (_, k) => cadd(A, cscale(csub(B, A), k / m)));
    const out = seg(b, p0, 200), ring = circleLoop(c, r, a0, steps, dir);
    return [...out, ...ring.slice(1), ...seg(p0, b, 200).slice(1)];
  }
  const sortFibre = (xs) => xs.slice().sort((a, b) => (Math.abs(a.re - b.re) > 1e-9 ? a.re - b.re : a.im - b.im));

  /* The Kummer cover x^n = t of G_m. Over t = 1 the fibre is μ_n, labelled by k for ζ^k. */
  function kummer(n) {
    return {
      degree: n,
      coeffs: (t) => [csub(C(0), t), ...Array(n - 1).fill(C(0)), C(1)],
      fibre: (t) => {
        const r = Math.pow(cabs(t), 1 / n), a = Math.atan2(t.im, t.re);
        return Array.from({ length: n }, (_, k) => cscale(cexpi((a + 2 * Math.PI * k) / n), r));
      },
    };
  }
  /* The loop once round 0 (equivalently, once round the cylinder G_m), based at 1. */
  const kummerMonodromy = (n, turns = 1) => monodromy(kummer(n), circleLoop(C(0), 1, 0, 360 * Math.max(1, Math.abs(turns)) * Math.max(2, n), turns || 1));

  /* A degree-3 cover of P¹ branched only over 0, 1, ∞: x ↦ g(x) = (1 − T₃(x))/2 with the Chebyshev
   * polynomial T₃(x) = 4x³ − 3x. Its fibre over t is the three roots of 2x³ − 1.5x − (0.5 − t). */
  const CHEB_BASE = C(0.5, 0.5);
  const chebyshev = {
    degree: 3,
    coeffs: (t) => [csub(t, C(0.5)), C(-1.5), C(0), C(2)],
    fibre(t) { return sortFibre(croots(this.coeffs(t))); },
    map: (x) => { const x3 = cmul(cmul(x, x), x); return csub(C(0.5), cscale(csub(cscale(x3, 4), cscale(x, 3)), 0.5)); },
  };
  /* Loops based at CHEB_BASE (upper half-plane): γ₀ and γ₁ are counterclockwise lassos round 0 and 1,
   * γ∞ is the big clockwise circle, so γ₀γ₁γ∞ = 1 in π₁(P¹ − {0,1,∞}). */
  function threePointLoops(base = CHEB_BASE) {
    return {
      g0: lassoLoop(base, C(0), 0.3, 1),
      g1: lassoLoop(base, C(1), 0.3, 1),
      ginf: lassoLoop(base, C(0.5), 3, -1, 1440),
    };
  }
  function chebyshevMonodromy() {
    const L = threePointLoops(), m = {};
    for (const k of ["g0", "g1", "ginf"]) m[k] = monodromy(chebyshev, L[k]).perm;
    return { ...m, fibre: chebyshev.fibre(CHEB_BASE), relation: compose(m.g0, m.g1, m.ginf) };
  }

  /* ---------------- covers from permutations: Schreier graphs, dessins, genus ---------------- */
  /* Regular (Galois-closure) action: the fibre is the group itself and generators act by right multiplication. */
  function regularAction(gens, n) {
    const G = generate(gens, n), key = (p) => p.join(","), index = new Map(G.map((g, i) => [key(g), i]));
    const act = gens.map((s) => G.map((g) => index.get(key(compose(g, s)))));
    return { elements: G, gens: act, size: G.length };
  }
  /* Edges i —s→ s(i) of the monodromy (Schreier) graph. */
  const schreierEdges = (gens, names) => gens.flatMap((g, k) => g.map((j, i) => ({ from: i, to: j, gen: names[k] })));
  /* A cover of P¹ branched over 0, 1, ∞ with monodromy (σ₀, σ₁, σ∞), σ₀σ₁σ∞ = 1, is a dessin:
   * black vertices are cycles of σ₀, white vertices cycles of σ₁, faces cycles of σ∞, edges the fibre.
   * Riemann–Hurwitz: 2 − 2g = #cycles(σ₀) + #cycles(σ₁) + #cycles(σ∞) − n. */
  function dessin(s0, s1) {
    const n = s0.length, sinf = inverse(compose(s0, s1));
    const nc = (p) => cycles(p, true).length;
    const chi = nc(s0) + nc(s1) + nc(sinf) - n;
    return { n, s0, s1, sinf, black: cycles(s0, true), white: cycles(s1, true), faces: cycles(sinf, true), genus: (2 - chi) / 2, connected: isTransitive([s0, s1], n) };
  }
  /* Riemann–Hurwitz for a degree-d cover of a genus-g compact curve with total ramification R = Σ(e − 1). */
  const hurwitzGenus = (gX, d, R = 0) => (d * (2 * gX - 2) + R + 2) / 2;

  /* ---------------- surfaces: presentations, polygons, Euler characteristic ---------------- */
  function surface(g, r) {
    if (!(Number.isInteger(g) && g >= 0 && Number.isInteger(r) && r >= 0)) throw new Error("genus and punctures are whole numbers.");
    const gens = [];
    for (let i = 1; i <= g; i++) gens.push(`a${i}`, `b${i}`);
    for (let j = 1; j <= r; j++) gens.push(`c${j}`);
    const relation = [];
    for (let i = 1; i <= g; i++) relation.push([`a${i}`, 1], [`b${i}`, 1], [`a${i}`, -1], [`b${i}`, -1]);
    for (let j = 1; j <= r; j++) relation.push([`c${j}`, 1]);
    const chi = 2 - 2 * g - r;
    const free = r > 0, rank = free ? 2 * g + r - 1 : null;
    let top, et;
    if (g === 0 && r <= 1) { top = "1"; et = "1"; }
    else if (free) { top = rank === 1 ? "ℤ" : `F${sub(rank)}`; et = rank === 1 ? "ℤ̂" : `F̂${sub(rank)}`; }
    else if (g === 1) { top = "ℤ²"; et = "ℤ̂²"; }
    else { top = `Π${sub(g)}`; et = `Π̂${sub(g)}`; }
    return { g, r, gens, relation, chi, free, rank, abelianRank: 2 * g + Math.max(r - 1, 0), top, et, eliminated: free ? `c${r}` : null };
  }
  const SUB = "₀₁₂₃₄₅₆₇₈₉", SUP = "⁰¹²³⁴⁵⁶⁷⁸⁹";
  function sub(n) { return String(n).split("").map((d) => SUB[+d]).join(""); }
  function sup(n) { return String(n).replace("-", "⁻").split("").map((d) => (d === "⁻" ? d : SUP[+d])).join(""); }
  const relationString = (S) => {
    const parts = [];
    for (let i = 1; i <= S.g; i++) parts.push(`[a${sub(i)},b${sub(i)}]`);
    for (let j = 1; j <= S.r; j++) parts.push(`c${sub(j)}`);
    return parts.length ? `${parts.join(" ")} = 1` : "no generators";
  };
  /* Free reduction of a word [[gen, ±1], ...]. */
  function reduceWord(w) {
    const out = [];
    for (const [x, e] of w) {
      const top = out[out.length - 1];
      if (top && top[0] === x && top[1] === -e) out.pop(); else out.push([x, e]);
    }
    return out;
  }
  const invWord = (w) => w.slice().reverse().map(([x, e]) => [x, -e]);
  /* Evaluate a word in permutations: images maps a generator to its permutation. */
  const evalWord = (w, images, n) => w.reduce((acc, [x, e]) => compose(acc, e > 0 ? images[x] : inverse(images[x])), identity(n));
  /* Eliminate the last puncture loop: c_r = (∏[aᵢ,bᵢ] c₁⋯c_{r−1})⁻¹, so the group is free on the rest. */
  function eliminateLast(S) {
    if (!S.free) return null;
    const head = S.relation.slice(0, -1);
    return { gen: S.eliminated, word: invWord(head), freeGens: S.gens.filter((x) => x !== S.eliminated) };
  }
  /* The 4g-gon a₁b₁a₁⁻¹b₁⁻¹⋯: glue paired edges and count the vertex classes and the Euler characteristic. */
  function polygon(g) {
    if (g < 1) throw new Error("The 4g-gon needs genus at least 1.");
    const edges = [];
    for (let i = 1; i <= g; i++) edges.push([`a${i}`, 1], [`b${i}`, 1], [`a${i}`, -1], [`b${i}`, -1]);
    const N = edges.length, parent = identity(N);
    const find = (x) => (parent[x] === x ? x : (parent[x] = find(parent[x])));
    const union = (a, b) => { parent[find(a)] = find(b); };
    // Edge k runs from vertex k to vertex k+1; its tail and head depend on its exponent.
    const ends = (k) => (edges[k][1] > 0 ? [k, (k + 1) % N] : [(k + 1) % N, k]);
    const byLabel = {};
    edges.forEach(([x], k) => (byLabel[x] ??= []).push(k));
    for (const [, [k1, k2]] of Object.entries(byLabel)) { const [t1, h1] = ends(k1), [t2, h2] = ends(k2); union(t1, t2); union(h1, h2); }
    const V = new Set(identity(N).map(find)).size, E = N / 2, F = 1;
    return { edges, V, E, F, chi: V - E + F, word: edges };
  }

  /* ---------------- complex tori and abelian varieties ---------------- */
  /* E = ℂ/Λ with Λ = ℤ + τℤ. The fibre of [n] over 0 is E[n] = (1/n)Λ/Λ: the points (i + jτ)/n. */
  function torsion(n, tau = C(0.3, 0.95)) {
    const pts = [];
    for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) pts.push({ i, j, z: cscale(cadd(C(i), cscale(tau, j)), 1 / n) });
    return pts;
  }
  /* Reduce z modulo Λ = ℤ + τℤ, returning lattice coordinates in [0,1)². */
  function lattCoords(z, tau) {
    const v = z.im / tau.im, u = z.re - v * tau.re;
    const fr = (x) => { const f = x - Math.floor(x); return f > 1 - 1e-9 ? 0 : f; };
    return [fr(u), fr(v)];
  }
  const torsionCount = (n, dim = 1) => Math.pow(n, 2 * dim);

  /* ---------------- finite fields F_p[x]/(f) ---------------- */
  const mod = (a, p) => ((a % p) + p) % p;
  const ptrim = (a) => { const b = a.slice(); while (b.length && b[b.length - 1] === 0) b.pop(); return b; };
  const padd = (a, b, p) => ptrim(Array.from({ length: Math.max(a.length, b.length) }, (_, i) => mod((a[i] || 0) + (b[i] || 0), p)));
  const psub = (a, b, p) => padd(a, b.map((x) => -x), p);
  function pmul(a, b, p) {
    if (!a.length || !b.length) return [];
    const r = new Array(a.length + b.length - 1).fill(0);
    a.forEach((x, i) => b.forEach((y, j) => { r[i + j] = mod(r[i + j] + x * y, p); }));
    return ptrim(r);
  }
  function invmod(a, p) { a = mod(a, p); for (let x = 1; x < p; x++) if ((a * x) % p === 1) return x; throw new Error("not invertible"); }
  function pdivmod(a, b, p) {
    let r = ptrim(a.map((x) => mod(x, p))); const q = [];
    const db = b.length - 1, inv = invmod(b[db], p);
    while (r.length - 1 >= db && r.length) {
      const k = r.length - 1 - db, c = mod(r[r.length - 1] * inv, p);
      q[k] = c;
      const s = new Array(k).fill(0).concat(b.map((x) => mod(x * c, p)));
      r = psub(r, s, p);
    }
    return { q: Array.from({ length: q.length }, (_, i) => q[i] || 0), r };
  }
  const pmod = (a, f, p) => pdivmod(a, f, p).r;
  function ppowmod(a, e, f, p) {
    let r = [1], b = pmod(a, f, p);
    for (let k = BigInt(e); k > 0n; k >>= 1n) { if (k & 1n) r = pmod(pmul(r, b, p), f, p); b = pmod(pmul(b, b, p), f, p); }
    return r;
  }
  function pgcd(a, b, p) { a = ptrim(a); b = ptrim(b); while (b.length) [a, b] = [b, pdivmod(a, b, p).r]; return a; }
  const primeFactors = (n) => { const f = []; for (let d = 2; d * d <= n; d++) if (n % d === 0) { f.push(d); while (n % d === 0) n /= d; } if (n > 1) f.push(n); return f; };
  const isPrime = (n) => Number.isInteger(n) && n >= 2 && primeFactors(n)[0] === n;
  /* Rabin's test: f of degree n is irreducible over F_p iff x^(p^n) ≡ x and gcd(x^(p^(n/r)) − x, f) = 1 for primes r | n. */
  function irreducible(f, p) {
    const n = f.length - 1;
    if (n < 1) return false;
    const x = pmod([0, 1], f, p);
    const xpk = (k) => ppowmod(x, BigInt(p) ** BigInt(k), f, p);
    if (!equalPoly(psub(xpk(n), x, p), [])) return false;
    for (const r of primeFactors(n)) { const g = pgcd(f, psub(xpk(n / r), x, p), p); if (g.length > 1) return false; }
    return true;
  }
  const equalPoly = (a, b) => { const x = ptrim(a), y = ptrim(b); return x.length === y.length && x.every((v, i) => v === y[i]); };
  /* The first monic irreducible polynomial of degree n over F_p, in lexicographic order of coefficients. */
  function firstIrreducible(n, p) {
    const total = p ** n;
    for (let m = 0; m < total; m++) {
      const c = []; let v = m;
      for (let i = 0; i < n; i++) { c.push(v % p); v = Math.floor(v / p); }
      const f = [...c, 1];
      if (irreducible(f, p)) return f;
    }
    throw new Error("no irreducible polynomial found");
  }
  function polyString(a, v = "α") {
    const t = ptrim(a);
    if (!t.length) return "0";
    const terms = [];
    for (let i = t.length - 1; i >= 0; i--) {
      if (!t[i]) continue;
      const mono = i === 0 ? "" : i === 1 ? v : `${v}${sup(i)}`;
      terms.push(i === 0 ? String(t[i]) : `${t[i] === 1 ? "" : t[i]}${mono}`);
    }
    return terms.join(" + ");
  }
  /* F_{p^n} = F_p[α]/(f(α)). The Frobenius orbit of α is its n conjugates α, α^p, …: the necklace of
   * the n embeddings F_{p^n} → F̄_p, rotated one step by x ↦ x^p, closing after exactly n steps. */
  function frobeniusNecklace(p, n) {
    if (!isPrime(p)) throw new Error("p must be prime.");
    const f = firstIrreducible(n, p), orbit = [], alpha = pmod([0, 1], f, p);
    let a = alpha;
    for (let k = 0; k < n; k++) { orbit.push(a); a = ppowmod(a, p, f, p); }
    const closes = equalPoly(a, alpha);
    const distinct = new Set(orbit.map((x) => ptrim(x).join(","))).size;
    return { p, n, f, fString: polyString(f, "x"), orbit, labels: orbit.map((x) => polyString(x)), closes, distinct, perm: identity(n).map((k) => (k + 1) % n) };
  }

  /* Artin–Schreier: y^p − y = t over A¹ in characteristic p. ∂/∂y = −1 never vanishes, so the cover is
   * étale everywhere on A¹; the deck group is F_p acting by y ↦ y + a. Over a closed point t ∈ F_p^×
   * the fibre is the field F_p[y]/(y^p − y − t), on which Frobenius acts as y ↦ y + t. */
  function artinSchreier(p, t) {
    if (!isPrime(p)) throw new Error("p must be prime.");
    t = mod(t, p);
    const f = [mod(-t, p), mod(-1, p), ...Array(p - 2).fill(0), 1];
    const derivative = mod(p, p) === 0 ? [mod(-1, p)] : null; // p·y^(p−1) − 1 = −1 in characteristic p
    const frob = t === 0 ? null : ppowmod([0, 1], p, f, p);
    const deck = identity(p).map((k) => (k + 1) % p);
    return {
      p, t, f, fString: polyString(f, "y"), derivative, irreducible: t !== 0 && irreducible(f, p),
      split: t === 0, frobenius: frob, frobeniusString: frob && polyString(frob, "y"), frobIsTranslation: frob ? equalPoly(frob, [t, 1]) : null,
      deck, deckCycle: cycleString(deck, identity(p).map((a) => (a === 0 ? "y" : `y+${a}`))),
    };
  }
  /* The same equation over ℂ: y^p − y = t branches where p·y^(p−1) = 1, over p − 1 distinct finite values of t. */
  function artinSchreierChar0(p) {
    const ys = Array.from({ length: p - 1 }, (_, k) => cscale(cexpi((2 * Math.PI * k) / (p - 1)), Math.pow(1 / p, 1 / (p - 1))));
    const ts = ys.map((y) => { let yp = C(1); for (let i = 0; i < p; i++) yp = cmul(yp, y); return csub(yp, y); });
    return { critical: ys, branch: ts };
  }

  /* ---------------- elliptic curves in characteristic p ---------------- */
  function legendre(a, p) { a = mod(a, p); if (a === 0) return 0; let r = 1, b = a; for (let e = (p - 1) / 2; e > 0; e >>= 1) { if (e & 1) r = (r * b) % p; b = (b * b) % p; } return r === 1 ? 1 : -1; }
  /* y² = x³ + ax + b over F_p (p ≥ 5): point count, trace of Frobenius a_p, Hasse invariant
   * (the coefficient of x^(p−1) in (x³ + ax + b)^((p−1)/2)), and ordinary or supersingular. */
  function ellipticModP(a, b, p) {
    if (!isPrime(p) || p < 5) throw new Error("Use a prime p ≥ 5.");
    const disc = mod(4 * a ** 3 + 27 * b ** 2, p);
    if (disc === 0) return { a, b, p, singular: true };
    let count = 1;
    for (let x = 0; x < p; x++) count += 1 + legendre(x * x * x + a * x + b, p);
    const ap = p + 1 - count;
    let pw = [1]; const f = [mod(b, p), mod(a, p), 0, 1];
    for (let k = 0; k < (p - 1) / 2; k++) pw = pmul(pw, f, p);
    const hasse = pw[p - 1] || 0;
    const supersingular = hasse === 0;
    return {
      a, b, p, singular: false, count, ap, hasse, supersingular,
      tateP: supersingular ? 0 : 1, tateL: 2,
      pTorsion: (k) => (supersingular ? 1 : p ** k), lTorsion: (l, k) => l ** (2 * k),
    };
  }
  /* p-rank and Tate-module ranks of an abelian variety of dimension g with p-rank f (0 ≤ f ≤ g). */
  const tateRanks = (g, f) => ({ l: 2 * g, p: f });

  /* ---------------- fields ---------------- */
  /* Spec ℝ: the fibre over the geometric point Spec ℂ is the two roots ±i of x² + 1, swapped by conjugation. */
  const specR = () => ({ fibre: [C(0, 1), C(0, -1)], conj: [1, 0], group: "C₂" });
  /* Spec ℂ: a finite étale ℂ-algebra is ℂⁿ (every polynomial splits), so the only connected one is ℂ itself. */
  function specC(n) { return { pieces: n, connected: n === 1 }; }

  /* ---------------- cyclotomic Galois action and the arithmetic fundamental group ---------------- */
  const units = (n) => (n === 1 ? [0] : identity(n).filter((a) => gcd(a, n) === 1));
  /* σ_a : ζ ↦ ζ^a permutes μ_n = {ζ^k}: k ↦ ak mod n. The geometric loop γ: k ↦ k + 1. */
  const galoisPerm = (n, a) => identity(n).map((k) => mod(a * k, n));
  const rotation = (n, s = 1) => identity(n).map((k) => mod(k + s, n));
  /* In π₁(G_{m,ℚ}) the Galois element σ_a conjugates the geometric loop to its a-th power. */
  const conjugationCheck = (n, a) => equal(compose(inverse(galoisPerm(n, a)), rotation(n), galoisPerm(n, a)), rotation(n, a));
  /* The cyclotomic character at level n and its compatibility with level m | n. */
  const reduceUnit = (a, n, m) => { if (n % m) throw new Error("m must divide n"); return mod(a, m); };

  /* ---------------- profinite completion of ℤ ---------------- */
  const divisors = (n) => identity(n + 1).filter((d) => d > 0 && n % d === 0);
  /* The tower ℤ/m → ℤ/n for n | m: reduction is a surjective homomorphism, and an integer has compatible images. */
  function zhatChain(levels) {
    return levels.map((n, i) => ({ n, next: levels[i + 1] ?? null, divides: levels[i + 1] ? n % levels[i + 1] === 0 : null }));
  }
  const imageInLevels = (x, levels) => levels.map((n) => mod(x, n));

  /* ---------------- the results table (Szamuely-style computations) ----------------
   * Assumptions are written exactly as the specification's computation set states them. */
  const RESULTS = [
    { id: "spec-c", X: "Spec ℂ", assumptions: "—", answer: "1", picture: "single algebraic point", kind: "schematic" },
    { id: "spec-r", X: "Spec ℝ", assumptions: "—", answer: "C₂", picture: "point with conjugate geometric fibre", kind: "schematic" },
    { id: "spec-fq", X: "Spec 𝔽_q", assumptions: "—", answer: "ℤ̂", picture: "finite-extension tower + Frobenius cycles", kind: "schematic" },
    { id: "p1", X: "ℙ¹", assumptions: "alg. closed, char 0", answer: "1", picture: "Riemann sphere", kind: "literal" },
    { id: "a1", X: "𝔸¹", assumptions: "alg. closed, char 0", answer: "1", picture: "sphere minus ∞, morphing to plane", kind: "literal" },
    { id: "gm", X: "𝔾ₘ", assumptions: "alg. closed, char 0", answer: "ℤ̂", picture: "sphere minus 0, ∞; punctured plane; cylinder; explicit n-sheeted cylinder cover", kind: "literal" },
    { id: "p1-3", X: "ℙ¹ − {0,1,∞}", assumptions: "alg. closed, char 0", answer: "F̂₂", picture: "sphere with three punctures + pair of pants", kind: "literal" },
    { id: "genus-g", X: "projective genus g curve", assumptions: "char 0", answer: "profinite surface group", picture: "g-handled surface", kind: "literal" },
    { id: "punctured-g", X: "punctured genus g curve", assumptions: "char 0", answer: "free profinite group of rank 2g+r−1", picture: "handles + actual holes", kind: "literal" },
    { id: "elliptic", X: "elliptic curve", assumptions: "alg. closed, char 0", answer: "ℤ̂²", picture: "cubic + lattice + torus; torus self-cover + n-torsion grid", kind: "literal" },
    { id: "abelian", X: "dimension-g abelian variety", assumptions: "char 0", answer: "ℤ̂²ᵍ", picture: "lattice quotient / product-torus schematic", kind: "analogy" },
    { id: "a1-p", X: "𝔸¹", assumptions: "char p", answer: "show Artin–Schreier quotient", picture: "affine line + p algebraic sheets", kind: "schematic" },
    { id: "ordinary", X: "ordinary elliptic curve", assumptions: "char p", answer: "show nonzero T_p", picture: "visible p-adic torsion tower", kind: "schematic" },
    { id: "supersingular", X: "supersingular elliptic curve", assumptions: "char p", answer: "show vanished étale T_p", picture: "missing étale p-adic tower", kind: "schematic" },
  ];
  const EXTRA_PICTURES = [
    { id: "arith", X: "arithmetic π₁", picture: "geometric layer + Galois layer", kind: "schematic" },
    { id: "gm-q", X: "𝔾ₘ/ℚ", picture: "roots of unity + Galois permutation", kind: "schematic" },
  ];

  /* What each page computation is, for the lab, the status bar and the gallery. */
  const OBJECTS = {
    "spec-c": { name: "Spec ℂ", field: "ℂ", char: "0", punctures: "—", models: ["point"], top: "—", et: "1", chapter: 1 },
    "spec-r": { name: "Spec ℝ", field: "ℝ", char: "0", punctures: "—", models: ["point"], top: "—", et: "C₂ = Gal(ℂ/ℝ)", chapter: 1 },
    "spec-fq": { name: "Spec 𝔽_q", field: "𝔽_q", char: "p", punctures: "—", models: ["tower"], top: "—", et: "ℤ̂ (Frobenius)", chapter: 1 },
    p1: { name: "ℙ¹", field: "ℂ", char: "0", punctures: "none", models: ["sphere", "plane + ∞"], top: "1", et: "1", chapter: 4 },
    a1: { name: "𝔸¹", field: "ℂ", char: "0", punctures: "∞", models: ["sphere − ∞", "plane"], top: "1", et: "1", chapter: 4 },
    gm: { name: "𝔾ₘ", field: "ℂ", char: "0", punctures: "0, ∞", models: ["cylinder", "punctured plane", "punctured sphere"], top: "ℤ", et: "ℤ̂", chapter: 4 },
    "p1-3": { name: "ℙ¹ − {0,1,∞}", field: "ℂ", char: "0", punctures: "0, 1, ∞", models: ["pair of pants", "punctured sphere", "plane − {0,1}"], top: "F₂", et: "F̂₂", chapter: 4 },
    curve: { name: "genus-g curve", field: "ℂ", char: "0", punctures: "r points", models: ["surface", "4g-gon"], top: "surface group", et: "profinite completion", chapter: 4 },
    elliptic: { name: "elliptic curve", field: "ℂ", char: "0", punctures: "none", models: ["torus", "lattice", "cubic"], top: "ℤ²", et: "ℤ̂²", chapter: 5 },
    abelian: { name: "abelian variety", field: "ℂ", char: "0", punctures: "none", models: ["product of tori", "lattice quotient"], top: "ℤ²ᵍ", et: "ℤ̂²ᵍ", chapter: 5 },
    "a1-p": { name: "𝔸¹ in char p", field: "𝔽̄_p", char: "p", punctures: "∞", models: ["algebraic line"], top: "no topology", et: "not finitely generated; ↠ ℤ/p", chapter: 5 },
    "ell-p": { name: "elliptic curve mod p", field: "𝔽̄_p", char: "p", punctures: "none", models: ["torsion towers"], top: "no topology", et: "ℓ-part ℤ_ℓ², p-part ℤ_p or 0", chapter: 5 },
    arith: { name: "𝔾ₘ over ℚ (arithmetic π₁)", field: "ℚ", char: "0", punctures: "0, ∞", models: ["two layers"], top: "—", et: "ℤ̂(1) ⋊ G_ℚ", chapter: 5 },
  };

  /* Szamuely, Galois Groups and Fundamental Groups (Cambridge Studies in Advanced Mathematics 117,
   * Cambridge University Press, 2009). Chapter titles as on the publisher's contents page; no
   * section or page numbers are cited. */
  const SZAMUELY = [
    { chapter: 1, title: "Galois theory of fields", topics: ["Galois theory", "finite étale algebras", "absolute Galois groups"], anchors: ["spec-c", "spec-r", "spec-fq"] },
    { chapter: 2, title: "Fundamental groups in topology", topics: ["covering spaces", "fundamental groups", "monodromy", "finite π₁-sets"], anchors: ["fibre", "monodromy"] },
    { chapter: 3, title: "Riemann surfaces", topics: ["Riemann surfaces", "complex algebraic curves", "topological models"], anchors: ["p1", "elliptic", "curve"] },
    { chapter: 4, title: "Fundamental groups of algebraic curves", topics: ["algebraic fundamental groups of curves", "comparison with topology", "punctured curves", "Galois action"], anchors: ["p1", "a1", "gm", "p1-3", "curve", "arith"] },
    { chapter: 5, title: "Fundamental groups of schemes", topics: ["fundamental groups of schemes", "geometric points", "fibre functors", "abelian varieties", "Tate modules"], anchors: ["a1-p", "abelian", "ell-p", "arith"] },
    { chapter: 6, title: "Tannakian fundamental groups", topics: ["beyond this page"], anchors: [] },
  ];

  const DICTIONARY = [
    ["finite separable extension L/K", "finite covering space Y → X", "finite étale cover Y → X"],
    ["Gal(K^s/K) = G_K", "π₁(X, x)", "π₁ᵉᵗ(X, x̄)"],
    ["finite G_K-sets", "finite π₁(X)-sets", "finite π₁ᵉᵗ(X)-sets"],
    ["embeddings L → K^s", "points of the fibre over x", "F_x̄(Y): geometric points over x̄"],
    ["Galois extension", "connected Galois (regular) cover", "connected Galois étale cover"],
    ["Gal(L/K)", "deck group Aut(Y/X)", "Aut(Y/X)"],
  ];

  const PROGRESSION = [
    "Fields have fundamental groups", "Covering spaces and fibres", "P¹ as a sphere", "A¹ as sphere minus ∞",
    "Gₘ as twice-punctured sphere", "Kummer covers", "profinite completion", "three-punctured sphere",
    "pair of pants → F₂", "genus-g surfaces", "elliptic curve: cubic → torus", "torsion covers",
    "geometric vs arithmetic π₁", "characteristic p", "Artin–Schreier surprise", "final dictionary",
  ];

  /* ---------------- the computation behind each lab view ---------------- */
  function compute(st) {
    const s = { obj: "gm", n: 3, g: 2, r: 3, p: 3, t: 1, dim: 2, q: 2, a: 3, ellA: -1, ellB: 0, ellP: 7, ...st };
    const o = OBJECTS[s.obj];
    if (!o) throw new Error(`Unknown object ${s.obj}`);
    const out = { obj: s.obj, object: o.name, field: o.field, char: o.char, punctures: o.punctures, top: o.top, et: o.et, chapter: o.chapter };
    switch (s.obj) {
      case "spec-c": Object.assign(out, { cover: "Spec ℂ[x]/(f) = ⊔ points", degree: s.n, fibreSize: s.n, monodromy: "id", connectedCovers: specC(s.n).connected ? "degree 1 only" : "none of degree > 1", quotient: "1" }); break;
      case "spec-r": { const r = specR(); Object.assign(out, { cover: "Spec ℂ → Spec ℝ", degree: 2, fibreSize: 2, monodromy: cycleString(r.conj, ["i", "−i"]), quotient: "C₂" }); break; }
      case "spec-fq": { const N = frobeniusNecklace(s.q, s.n); Object.assign(out, { cover: `Spec 𝔽_${s.q}${sup(s.n)} → Spec 𝔽_${s.q}`, degree: s.n, fibreSize: s.n, monodromy: cycleString(N.perm), quotient: `ℤ/${s.n}`, necklace: N }); break; }
      case "p1": Object.assign(out, { cover: `degree ${s.n} unramified?`, degree: s.n, fibreSize: s.n, monodromy: "—", quotient: "1", hurwitz: hurwitzGenus(0, s.n), note: `An unramified connected degree-${s.n} cover would have genus ${hurwitzGenus(0, s.n)} < 0: impossible.` }); break;
      case "a1": Object.assign(out, { cover: "none nontrivial", degree: 1, fibreSize: 1, monodromy: "id", quotient: "1" }); break;
      case "gm": { const m = kummerMonodromy(s.n); Object.assign(out, { cover: `z ↦ z${sup(s.n)}`, degree: s.n, fibreSize: s.n, monodromy: cycleString(m.perm), quotient: `ℤ/${s.n}`, perm: m.perm }); break; }
      case "p1-3": { const ra = regularAction([parseCycles("(1 2)", 3), parseCycles("(1 2 3)", 3)], 3); Object.assign(out, { cover: "Galois S₃-cover (a ↦ (12), b ↦ (123))", degree: 6, fibreSize: 6, monodromy: `a: ${cycleString(ra.gens[0])}, b: ${cycleString(ra.gens[1])}`, quotient: "S₃", generators: "a, b" }); break; }
      case "curve": { const S = surface(s.g, s.r); Object.assign(out, { cover: "finite quotients of the surface group", degree: "—", fibreSize: "—", monodromy: relationString(S), quotient: S.free ? `free of rank ${S.rank}` : `one relator, ${S.gens.length} generators`, top: S.top, et: S.et, punctures: s.r ? `${s.r} points` : "none", generators: S.gens.join(", ") }); break; }
      case "elliptic": Object.assign(out, { cover: `[${s.n}] : E → E`, degree: s.n * s.n, fibreSize: s.n * s.n, monodromy: `translations by E[${s.n}] ≅ (ℤ/${s.n})²`, quotient: `(ℤ/${s.n})²` }); break;
      case "abelian": Object.assign(out, { cover: `[${s.n}] : A → A, dim ${s.dim}`, degree: torsionCount(s.n, s.dim), fibreSize: torsionCount(s.n, s.dim), monodromy: `translations by A[${s.n}] ≅ (ℤ/${s.n})${sup(2 * s.dim)}`, quotient: `(ℤ/${s.n})${sup(2 * s.dim)}`, top: `ℤ${sup(2 * s.dim)}`, et: `ℤ̂${sup(2 * s.dim)}` }); break;
      case "a1-p": { const A = artinSchreier(s.p, s.t); Object.assign(out, { cover: `y${sup(s.p)} − y = t`, degree: s.p, fibreSize: s.p, monodromy: A.deckCycle, quotient: `ℤ/${s.p}`, char: String(s.p), field: `𝔽̄${sub(s.p)}`, artin: A }); break; }
      case "ell-p": { const E = ellipticModP(s.ellA, s.ellB, s.ellP); Object.assign(out, { cover: `[${s.ellP}] : E → E`, degree: s.ellP * s.ellP, fibreSize: E.singular ? "—" : `${E.supersingular ? 1 : s.ellP} étale points`, monodromy: E.singular ? "singular" : E.supersingular ? "supersingular: E[p](𝔽̄_p) = 0" : "ordinary: E[p](𝔽̄_p) ≅ ℤ/p", quotient: E.singular ? "—" : E.supersingular ? "T_p = 0" : "T_p ≅ ℤ_p", char: String(s.ellP), field: `𝔽̄${sub(s.ellP)}`, elliptic: E }); break; }
      case "arith": { const ok = conjugationCheck(s.n, s.a); Object.assign(out, { cover: `x${sup(s.n)} = t over ℚ`, degree: s.n, fibreSize: s.n, monodromy: `γ: ${cycleString(rotation(s.n), labelsMu(s.n))}; σ_${s.a}: ${cycleString(galoisPerm(s.n, s.a), labelsMu(s.n))}`, quotient: `ℤ/${s.n} ⋊ (ℤ/${s.n})^×`, conjugation: ok }); break; }
    }
    return out;
  }
  const labelsMu = (n) => identity(n).map((k) => (k === 0 ? "1" : k === 1 ? "ζ" : `ζ${sup(k)}`));

  /* ---------------- the beamdswitch report ----------------
   * The talk follows the presentation progression and ends on the computation the page shows. */
  const say = (s) => String(s)
    .replace(/π₁ᵉᵗ/g, "the étale fundamental group").replace(/π₁/g, "the fundamental group")
    .replace(/ℤ̂/g, "zed hat").replace(/F̂₂/g, "the profinite free group on two generators").replace(/ℤ/g, "zed")
    .replace(/𝔾ₘ/g, "G m").replace(/ℙ¹/g, "P one").replace(/𝔸¹/g, "A one").replace(/𝔽/g, "F").replace(/ℂ/g, "C").replace(/ℝ/g, "R").replace(/ℚ/g, "Q")
    .replace(/[₀-₉]/g, (d) => ` ${SUB.indexOf(d)}`).replace(/[⁰-⁹¹²³]/g, (d) => ` to the ${"⁰¹²³⁴⁵⁶⁷⁸⁹".indexOf(d)}`)
    .replace(/[×·°σ∠⁻]/g, " ").replace(/[$\\`*_#|<>]/g, " ").replace(/\s+/g, " ").trim();
  function report(st) {
    const r = compute(st), n = st?.n ?? 3;
    const gm = kummerMonodromy(n), cheb = chebyshevMonodromy(), S = surface(st?.g ?? 2, st?.r ?? 3);
    const frame = (title, body, narration, extra = {}) => ({ title, body, narration, ...extra });
    return {
      meta: { title: "Étale fundamental group: from loops to covers to Galois symmetry", subtitle: `Current computation: ${r.object}`, author: "teoyujie.org", date: "", voice: "bf_emma" },
      narration: "This talk follows the étale fundamental group from loops, to finite covers, to Galois symmetry, with every computation drawn as geometry first.",
      setup: [
        frame("Fields have fundamental groups", "- Field theory, topology and algebraic geometry share one dictionary: finite separable extensions, finite covering spaces and finite étale covers.\n- $\\pi_1^{\\text{ét}}(\\operatorname{Spec} K, \\bar K) = G_K = \\operatorname{Gal}(K^s/K)$.",
          "Finite separable field extensions, finite covering spaces and finite étale covers are three versions of the same idea. In each, a group acts on the points of a fibre, and for a field that group is the absolute Galois group."),
        frame("Covering spaces and fibres", "- Pick a geometric point $\\bar x$ and look at the fibre $F_{\\bar x}(Y)$ of a finite cover $Y \\to X$.\n- A loop at $\\bar x$ permutes the fibre: monodromy $\\rho : \\pi_1(X, \\bar x) \\to S_n$.",
          "Choose a point on the base and look at the finitely many points above it. Walking once round a loop carries those points back to the fibre, but possibly permuted. That permutation is the monodromy."),
      ],
      method: [
        frame("P one is a sphere, A one is the sphere minus infinity", "- Stereographic projection identifies $\\mathbf P^1(\\mathbf C)$ with $S^2$; removing $\\infty$ leaves the plane $\\mathbf A^1$.\n- In characteristic 0 neither has a nontrivial connected finite étale cover.",
          "The projective line over the complex numbers is a sphere, with infinity at the north pole. Deleting infinity unrolls it to the plane, which contracts to a point, so neither has a nontrivial finite covering."),
        frame(`G m is a cylinder, and z to the n is an n-sheeted cover`, `- $\\mathbf G_m = \\mathbf P^1 - \\{0, \\infty\\}$, a twice-punctured sphere or a cylinder.\n- For $n = ${n}$ the loop once round the cylinder lifts to the permutation ${cycleString(gm.perm)} of the fibre $\\mu_{${n}}$.`,
          `Removing zero and infinity leaves a cylinder. The map z to the ${n} winds a cylinder ${n} times round it, and one loop round the base rotates the ${n} points of the fibre cyclically.`),
        frame("P one minus three points is a pair of pants", `- Loops $\\gamma_0, \\gamma_1, \\gamma_\\infty$ round the three cuffs satisfy $\\gamma_0\\gamma_1\\gamma_\\infty = 1$, leaving $F_2$.\n- The page lifts the three loops through the degree-3 Chebyshev cover: $\\gamma_0 \\mapsto ${cycleString(cheb.g0)}$, $\\gamma_1 \\mapsto ${cycleString(cheb.g1)}$, $\\gamma_\\infty \\mapsto ${cycleString(cheb.ginf)}$, product ${cycleString(cheb.relation)}.`,
          "Three punctures make a pair of pants. Loops round the three cuffs multiply to the identity, so two of them generate a free group. Lifting them through a degree three cover gives two transpositions and a three cycle whose product is the identity."),
        frame(`Genus ${S.g} with ${S.r} punctures`, `- Generators ${S.gens.join(", ")} with relation $\\prod [a_i, b_i] \\prod c_j = 1$.\n- ${S.free ? `Eliminating $c_{${S.r}}$ leaves a free group of rank $2g + r - 1 = ${S.rank}$.` : "With no punctures it is a one-relator surface group."}`,
          `Every handle contributes two loops and every puncture one more, tied together by a single relation. ${S.free ? `With punctures one loop can be eliminated, leaving a free group of rank ${S.rank}.` : "Without punctures the relation stays, giving a surface group."}`),
      ],
      results: [
        frame("Elliptic curves and torsion covers", `- $E(\\mathbf C) \\cong \\mathbf C/\\Lambda$ is a torus with $\\pi_1 = \\mathbf Z^2$.\n- $[${n}] : E \\to E$ has fibre $E[${n}] \\cong (\\mathbf Z/${n})^2$, ${n * n} points.\n- $\\pi_1^{\\text{ét}}(E) \\cong \\widehat{\\mathbf Z}^2$.`,
          `The cubic curve is a torus, a lattice quotient of the plane. Multiplication by ${n} is a cover of degree ${n * n}, and its fibre over zero is a ${n} by ${n} grid of torsion points.`),
        frame("Characteristic p: the Artin–Schreier surprise", `- $y^p - y = t$ has $\\partial/\\partial y = -1$: étale over all of $\\mathbf A^1$, deck group $\\mathbf Z/p$ by $y \\mapsto y + 1$.\n- So $\\pi_1^{\\text{ét}}(\\mathbf A^1)$ in characteristic $p$ is nontrivial (and not finitely generated); only the $\\mathbf Z/p$ quotients are shown.`,
          "In characteristic p the affine line has finite étale covers that have no topological analogue. The Artin Schreier equation has a derivative that never vanishes, so its p sheets never meet."),
        frame(`Current computation: ${r.object}`, `- Cover: ${r.cover}.\n- Degree ${r.degree}, fibre size ${r.fibreSize}.\n- Monodromy: ${r.monodromy}.\n- Finite quotient read off: ${r.quotient}; étale fundamental group ${r.et}.`,
          say(`The page currently shows ${r.object}. Its cover has degree ${r.degree}, and the finite quotient read from the fibre is ${r.quotient}.`)),
      ],
      checks: [
        frame("What the page checks", `- The loop round $\\mathbf G_m$ gives an ${n}-cycle by numerical path lifting.\n- The $S_3$ cover with $a \\mapsto (12)$, $b \\mapsto (123)$ has a transitive 6-point Schreier graph.\n- $|E[n]| = n^2$; punctured genus $g$ gives free rank $2g + r - 1$; the 4g-gon glues to one vertex.\n- Ordinary curves in characteristic $p$ have étale $T_p$ of rank 1, supersingular of rank 0; $T_\\ell$ has rank 2.`,
          "Every number on the page is computed, not typed in. The monodromy comes from lifting loops through explicit equations, the torsion points are counted on the lattice, and the Tate module ranks follow from the Hasse invariant.",
          { key: "To compute the étale fundamental group of $X$, understand the finite étale covers of $X$: draw the curve, draw its covers, look at one fibre, watch it permute, and collect every finite monodromy group." }),
      ],
    };
  }

  return {
    identity, compose, inverse, equal, power, cycles, order, cycleType, cycleString, parseCycles, orbits, isTransitive, generate, centralizer, gcd, lcm,
    C, cadd, csub, cmul, cdiv, cabs, cexpi, cscale, cpoly, croots,
    liftPath, monodromy, circleLoop, lassoLoop, kummer, kummerMonodromy, chebyshev, CHEB_BASE, threePointLoops, chebyshevMonodromy,
    regularAction, schreierEdges, dessin, hurwitzGenus,
    surface, relationString, reduceWord, invWord, evalWord, eliminateLast, polygon, sub, sup,
    torsion, lattCoords, torsionCount,
    mod, pmul, pmod, ppowmod, pgcd, irreducible, firstIrreducible, polyString, frobeniusNecklace, isPrime, equalPoly,
    artinSchreier, artinSchreierChar0, legendre, ellipticModP, tateRanks,
    specR, specC, units, galoisPerm, rotation, conjugationCheck, reduceUnit, divisors, zhatChain, imageInLevels, labelsMu,
    RESULTS, EXTRA_PICTURES, OBJECTS, SZAMUELY, DICTIONARY, PROGRESSION, compute, report, say,
  };
});
