// The globals Good food in Ubi, Hougang, Woodleigh, Paya Lebar and Eunos's page scripts read, for type checking only: each is a file the page inlines unchanged.
// Generated by scripts/new_visual.py; --update rewrites this file.
declare var VisualKit: typeof import("../../../scripts/kit/kit.js");
declare var Model: typeof import("../src/model.js");
declare var Report: typeof import("../report.js");
