/* Connes QFT laboratory: finite operator algebras, modular theory and the geometry of local regions.
 *
 * Finite models only, said so wherever the page shows them: *-algebras of matrices (every finite-
 * dimensional von Neumann algebra is a direct sum of full matrix algebras, so these are type I),
 * commutants by solving TA = AT, the Tomita–Takesaki construction for a faithful state on M_n, modular
 * spectra of finite products of Powers/Araki–Woods states (which approximate the type III_λ and III₁
 * invariants), and the causal geometry of double cones and wedges in 1+1-dimensional Minkowski space.
 */
(function (factory) {
  if (typeof module === "object" && module.exports) module.exports = factory(require("./core.js"), require("./linalg.js"));
  else factory(self.ConnesQFT, self.ConnesQFT.linalg);
})(function (Q, LA) {
  "use strict";
  const PI = Math.PI;

  /* ---------- Pauli strings ---------- */
  const PAULI = { I: LA.eye(2), X: LA.from([[0, 1], [1, 0]]), Y: LA.from([[0, [0, -1]], [[0, 1], 0]]), Z: LA.from([[1, 0], [0, -1]]) };
  const pauliString = (s) => LA.kronAll(...s.split("").map((ch) => PAULI[ch]));
  /* All 4^k Pauli strings on k qubits, as labels. */
  function pauliLabels(k) { let out = [""]; for (let i = 0; i < k; i++) out = out.flatMap((p) => ["I", "X", "Y", "Z"].map((c) => p + c)); return out; }
  /* Two Pauli strings commute iff they anticommute on an even number of sites. */
  const pauliCommute = (a, b) => a.split("").filter((c, i) => c !== "I" && b[i] !== "I" && c !== b[i]).length % 2 === 0;

  /* ---------- algebras as subspaces of M_n ---------- */
  /* The *-algebra generated by a set of matrices: span closed under products and adjoints (with 1). Returns an orthonormal basis (as vectors). */
  function generateAlgebra(gens, n) {
    let basis = LA.orthonormalize([LA.vec(LA.eye(n)), ...gens.flatMap((g) => [LA.vec(g), LA.vec(LA.adj(g))])]);
    for (let round = 0; round < 8; round++) {
      const mats = basis.map((v) => LA.unvec(v, n));
      const prods = [];
      for (const A of mats) for (const B of mats) prods.push(LA.vec(LA.mul(A, B)));
      const next = LA.orthonormalize([...basis, ...prods]);
      if (next.length === basis.length) break;
      basis = next;
    }
    return basis;
  }
  /* Commutant {T : TA = AT for every A in the set}: the null space of T ↦ ([A_i, T])_i. */
  function commutant(gens, n) {
    const rows = [];
    for (const A of gens) for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) {
      // ([A, T])_{ij} = ∑_k A_ik T_kj − T_ik A_kj, linear in vec(T)
      const row = Array.from({ length: n * n }, () => [0, 0]);
      for (let k = 0; k < n; k++) {
        const a = LA.get(A, i, k); row[k * n + j] = LA.C.add(row[k * n + j], a);
        const b = LA.get(A, k, j); row[i * n + k] = LA.C.sub(row[i * n + k], b);
      }
      rows.push(row);
    }
    const M = LA.from(rows);
    return LA.orthonormalize(LA.nullspace(M, 1e-9));
  }
  const dimOf = (basis) => basis.length;
  /* Intersection of two subspaces of M_n (as orthonormal bases): solve ∑ a_i u_i = ∑ b_j v_j. */
  function intersect(U, V, n) {
    if (!U.length || !V.length) return [];
    const N = n * n, cols = U.length + V.length;
    const M = LA.zeros(N, cols);
    U.forEach((u, c) => u.forEach((x, r) => LA.set(M, r, c, x)));
    V.forEach((v, c) => v.forEach((x, r) => LA.set(M, r, U.length + c, [-x[0], -x[1]])));
    const ns = LA.nullspace(M, 1e-9);
    return LA.orthonormalize(ns.map((coef) => Array.from({ length: N }, (_, r) => U.reduce((s, u, c) => LA.C.add(s, LA.C.mul(coef[c], u[r])), [0, 0]))));
  }
  /* Does a matrix lie in the span of a basis? */
  function inSpan(basis, A) {
    const v = LA.vec(A);
    let r = v.map((x) => x.slice());
    for (const u of basis) { const c = LA.vdot(u, r); r = r.map((x, i) => LA.C.sub(x, LA.C.mul(c, u[i]))); }
    return LA.vnorm(r) <= 1e-8 * Math.max(1, LA.vnorm(v));
  }
  /* Full analysis of the algebra generated by `gens`: M, M′, M″, centre, factor test. */
  function analyseAlgebra(gens, n) {
    const M = generateAlgebra(gens, n);
    const Mmats = M.map((v) => LA.unvec(v, n));
    const Mp = commutant(Mmats, n);
    const Mpp = commutant(Mp.map((v) => LA.unvec(v, n)), n);
    const Z = intersect(M, Mp, n);
    return { n, dimM: M.length, dimMprime: Mp.length, dimMbiprime: Mpp.length, dimCentre: Z.length, factor: Z.length === 1, bicommutantEqual: Mpp.length === M.length && M.every((v) => inSpan(Mpp, LA.unvec(v, n))), M, Mprime: Mp, Mbiprime: Mpp, centre: Z };
  }
  /* Local algebra of a set of sites in a chain of k qubits: generated by X and Z on those sites (M_2^{⊗|sites|} ⊗ 1). */
  function siteAlgebraGenerators(sites, k) {
    const gens = [];
    for (const s of sites) for (const P of ["X", "Z"]) gens.push(pauliString(Q.range(k).map((i) => (i === s ? P : "I")).join("")));
    return gens;
  }
  /* Locality check: largest ‖[A, B]‖ over generators of the two site algebras. */
  function localityCheck(sitesA, sitesB, k) {
    const ga = siteAlgebraGenerators(sitesA, k), gb = siteAlgebraGenerators(sitesB, k);
    let worst = 0;
    for (const A of ga) for (const B of gb) worst = Math.max(worst, LA.fnorm(LA.comm(A, B)));
    return { commute: worst < 1e-12, worst };
  }

  /* ---------- cyclic and separating vectors ---------- */
  /* Ω = ∑ √p_i e_i ⊗ e_i in ℂⁿ ⊗ ℂⁿ for M = M_n ⊗ 1: dim(MΩ) = n·rank, cyclic iff all p_i > 0;
     separating for M iff cyclic for M′ = 1 ⊗ M_n, i.e. iff the same rank condition holds. */
  function cyclicSeparating(p) {
    const n = p.length, rank = p.filter((x) => x > 1e-12).length;
    return { n, schmidtRank: rank, dimMOmega: n * rank, dimH: n * n, cyclic: rank === n, separating: rank === n };
  }

  /* ---------- Tomita–Takesaki for (M_n, ω_ρ) ---------- */
  /* H = M_n with ⟨X, Y⟩ = Tr(X*Y), M acting by left multiplication, Ω = ρ^{1/2}.
     S(AΩ) = A*Ω, i.e. S X = ρ^{-1/2} X* ρ^{1/2}. Write S = K∘T with K entrywise conjugation and T linear;
     then Δ = S*S = T*T and J = S Δ^{-1/2}. The closed forms are Δ X = ρ X ρ^{-1} and J X = X*. */
  function tomita(rho) {
    const n = rho.n, N = n * n;
    const { values: pv, vectors: V } = LA.eigh(rho);
    if (pv[0] <= 1e-12) throw new Error("tomita needs a faithful (full-rank) density matrix");
    const rpow = (s) => LA.mul(LA.mul(V, LA.diag(pv.map((p) => Math.pow(p, s)))), LA.adj(V));
    const rh = rpow(0.5), rmh = rpow(-0.5);
    // T X = conj(ρ^{-1/2}) X^T conj(ρ^{1/2}); S X = conj(T X)
    const T = LA.zeros(N);
    for (let c = 0; c < N; c++) {
      const E = LA.zeros(n); E.re[c] = 1;
      const TX = LA.mul(LA.mul(LA.conj(rmh), LA.transpose(E)), LA.conj(rh));
      for (let r = 0; r < N; r++) { T.re[r * N + c] = TX.re[r]; T.im[r * N + c] = TX.im[r]; }
    }
    const S = (X) => LA.conj(LA.unvec(LA.matvec(T, LA.vec(X)), n));
    const Delta = LA.mul(LA.adj(T), T);
    const { values: dv, vectors: W } = LA.eigh(Delta);
    const DeltaPow = (s) => LA.mul(LA.mul(W, LA.diag(dv.map((d) => Math.pow(d, s)))), LA.adj(W));
    const Dmh = DeltaPow(-0.5);
    const J = (X) => S(LA.unvec(LA.matvec(Dmh, LA.vec(X)), n)); // J = S Δ^{-1/2}
    const DeltaClosed = (X) => LA.mul(LA.mul(rho, X), LA.mul(LA.mul(V, LA.diag(pv.map((p) => 1 / p))), LA.adj(V)));
    // checks on a probe matrix
    const probe = LA.from(Q.range(n).map((i) => Q.range(n).map((j) => [Math.cos(1 + 2 * i + 3 * j), Math.sin(2 + i - j)])));
    const Omega = rh;
    const A = probe;
    const check = {
      tomita: LA.maxAbsDiff(S(LA.mul(A, Omega)), LA.mul(LA.adj(A), Omega)),
      polar: LA.maxAbsDiff(J(LA.unvec(LA.matvec(DeltaPow(0.5), LA.vec(probe)), n)), S(probe)),
      deltaClosedForm: LA.maxAbsDiff(LA.unvec(LA.matvec(Delta, LA.vec(probe)), n), DeltaClosed(probe)),
      jIsAdjoint: LA.maxAbsDiff(J(probe), LA.adj(probe)),
      jSquared: LA.maxAbsDiff(J(J(probe)), probe),
      jOmega: LA.maxAbsDiff(J(Omega), Omega),
    };
    // modular spectrum: eigenvalues of Δ are p_i/p_j; K = −log Δ
    const ratios = [];
    pv.forEach((a) => pv.forEach((b) => ratios.push(a / b)));
    return { n, rho, Omega, S, J, Delta, deltaEigenvalues: dv, ratios: ratios.sort((a, b) => a - b), K: dv.map((d) => -Math.log(d)), check, rhoEigenvalues: pv, rhoPow: rpow };
  }
  /* Modular flow σ_t(A) = Δ^{it} A Δ^{-it} = ρ^{it} A ρ^{-it} (acting on M by conjugation). */
  function modularFlow(rho, A, t) {
    const { values: pv, vectors: V } = LA.eigh(rho);
    const U = LA.mul(LA.mul(V, LA.diag(pv.map((p) => LA.C.polar(1, t * Math.log(p))))), LA.adj(V));
    return LA.mul(LA.mul(U, A), LA.adj(U));
  }
  /* KMS check at β = −1 in Takesaki's convention: ω(A σ_{−i}(B)) = ω(BA), with σ_{−i}(B) = ρ B ρ^{-1}. */
  function kmsCheck(rho, A, B) {
    const T = tomita(rho);
    const rinv = T.rhoPow(-1);
    const omega = (X) => LA.trace(LA.mul(rho, X));
    const lhs = omega(LA.mul(A, LA.mul(LA.mul(rho, B), rinv)));
    const rhs = omega(LA.mul(B, A));
    return { lhs, rhs, diff: Math.hypot(lhs[0] - rhs[0], lhs[1] - rhs[1]) };
  }
  /* Bloch vector of a 2×2 Hermitian traceless part: A = a₀ + a·σ ↦ a. */
  function blochVector(A) { const tr = (P) => LA.trace(LA.mul(PAULI[P], A))[0] / 2; return [tr("X"), tr("Y"), tr("Z")]; }
  /* Thermal qubit ρ = diag(p, 1 − p). */
  const qubitState = (p) => LA.diag([p, 1 - p]);

  /* ---------- type I / II / III ---------- */
  /* Traces of projections: M_n (type I_n) has normalized traces k/n; the hyperfinite II₁ factor, as the
     limit of M_{2^k}, has every dyadic rational k/2^m in [0, 1]. */
  const typeITraces = (n) => Q.range(n + 1).map((k) => k / n);
  const dyadicTraces = (m) => Q.range(2 ** m + 1).map((k) => k / 2 ** m);
  /* Modular spectrum of a finite Araki–Woods product ⊗_k (M_2, diag(1, λ_k)/(1+λ_k)): Δ eigenvalues are products of λ_k^{±1, 0}.
     For all λ_k = λ the logs fill λ^ℤ (Powers factor R_λ, type III_λ); two λ's with irrational log ratio make the
     generated group dense in ℝ₊ (type III₁). Returns the log-spectrum of the finite truncation. */
  function arakiWoodsLogSpectrum(lambdas) {
    let logs = [0];
    for (const l of lambdas) logs = logs.flatMap((x) => [x, x + Math.log(l), x - Math.log(l)]);
    const uniq = [...new Set(logs.map((x) => Math.round(x * 1e9) / 1e9))].sort((a, b) => a - b);
    return uniq;
  }
  const TYPE_INFO = [
    { id: "I", name: "Type I", projections: "minimal projections exist (rank-one projections in B(H))", trace: "trace takes values in {0, 1, …, n} (or ℕ ∪ {∞})", modular: "inner modular flow; finite systems in quantum mechanics" },
    { id: "II", name: "Type II", projections: "no minimal projections; projections divisible without end", trace: "a faithful trace exists: values fill [0, 1] (II₁) or [0, ∞] (II_{∞})", modular: "modular flow is inner (trace-scaled)" },
    { id: "III", name: "Type III", projections: "every nonzero projection is equivalent to the identity: no finite projections at all", trace: "no semifinite trace; only the modular data distinguish III₀, III_λ, III₁", modular: "Connes' invariant S(M) = ∩ spectra of Δ_φ: {0, 1} (III₀), {0} ∪ λ^{ℤ} (III_{λ}), [0, ∞) (III₁)" },
  ];

  /* ---------- causal geometry in 1+1 dimensions ---------- */
  /* A double cone (diamond) with centre (t, x) and radius r: in light-cone coordinates u = t − x, v = t + x it is
     [u − r, u + r] × [v − r, v + r]. */
  const diamond = (t, x, r) => ({ t, x, r, u: [t - x - r, t - x + r], v: [t + x - r, t + x + r] });
  /* Relation of two diamonds: "inside" (D1 ⊂ D2), "contains", "spacelike" (every pair of points spacelike), "timelike/overlap" otherwise. */
  function diamondRelation(d1, d2) {
    const sub = (a, b) => a[0] >= b[0] - 1e-12 && a[1] <= b[1] + 1e-12;
    if (sub(d1.u, d2.u) && sub(d1.v, d2.v)) return "inside";
    if (sub(d2.u, d1.u) && sub(d2.v, d1.v)) return "contains";
    // spacelike: one is entirely to the right of the other (Δu < 0 and Δv > 0 for all points, or the reverse)
    if ((d1.u[0] >= d2.u[1] && d1.v[1] <= d2.v[0]) || (d2.u[0] >= d1.u[1] && d2.v[1] <= d1.v[0])) return "spacelike";
    const overlapU = d1.u[0] < d2.u[1] && d2.u[0] < d1.u[1], overlapV = d1.v[0] < d2.v[1] && d2.v[0] < d1.v[1];
    return overlapU && overlapV ? "overlap" : "causal";
  }
  /* Sites of a lattice chain (spacing a, sites at x = (k − (K−1)/2) a) lying in the t = 0 base of a diamond. */
  const baseSites = (d, K, a = 1) => Q.range(K).filter((k) => { const x = (k - (K - 1) / 2) * a; return Math.abs(d.t) < 1e-9 && x >= d.x - d.r - 1e-9 && x <= d.x + d.r + 1e-9; });
  /* Right Rindler wedge W = {x > |t|} and the boost orbit through (t, x) inside it: Λ(η)(t, x) = (t cosh η + x sinh η, t sinh η + x cosh η).
     Bisognano–Wichmann: for the vacuum and the wedge algebra, Δ^{it} = U(Λ(−2πt)) (Bisognano & Wichmann 1975, 1976). */
  const inWedge = ([t, x]) => x > Math.abs(t);
  const boost = (eta, [t, x]) => [t * Math.cosh(eta) + x * Math.sinh(eta), t * Math.sinh(eta) + x * Math.cosh(eta)];
  const modularBoost = (tMod, p) => boost(-2 * PI * tMod, p);

  /* ---------- UV entanglement of the vacuum: harmonic chain ---------- */
  /* Chain of N oscillators with mass m and nearest-neighbour coupling (Dirichlet ends), K = (m² + 2)δ − δ_{i,i±1}.
     Ground state: X = ⟨φφ⟩ = ½K^{−1/2}, P = ⟨ππ⟩ = ½K^{1/2}. For a block of ℓ sites, the symplectic eigenvalues ν of
     √(X_A P_A) give S = ∑ (ν + ½)log(ν + ½) − (ν − ½)log(ν − ½) (Peschel 2003; Casini & Huerta 2009). */
  const ENT_CACHE = new Map();
  function chainEntanglement(N, ell, m) {
    const key = `${N}|${ell}|${m}`;
    if (!ENT_CACHE.has(key)) ENT_CACHE.set(key, chainEntanglementUncached(N, ell, m));
    return ENT_CACHE.get(key);
  }
  function chainEntanglementUncached(N, ell, m) {
    const w = Q.range(N).map((k) => Math.sqrt(m * m + 2 - 2 * Math.cos((PI * (k + 1)) / (N + 1))));
    const vec = (k, i) => Math.sqrt(2 / (N + 1)) * Math.sin((PI * (k + 1) * (i + 1)) / (N + 1));
    const start = Math.floor((N - ell) / 2);
    const idx = Q.range(ell).map((i) => start + i);
    const X = idx.map((i) => idx.map((j) => Q.sum(Q.range(N).map((k) => (vec(k, i) * vec(k, j)) / (2 * w[k])))));
    const P = idx.map((i) => idx.map((j) => Q.sum(Q.range(N).map((k) => (vec(k, i) * vec(k, j) * w[k]) / 2))));
    // eigenvalues of X P = squares of symplectic eigenvalues; symmetrize as X^{1/2} P X^{1/2}
    const ex = LA.eighReal(X);
    const sq = ex.vectors.map((row) => row.map((v) => v));
    const Xh = idx.map((_, i) => idx.map((__, j) => Q.sum(ex.values.map((lv, k) => sq[i][k] * Math.sqrt(Math.max(0, lv)) * sq[j][k]))));
    const M = Xh.map((r) => idx.map((_, j) => Q.sum(r.map((v, k) => v * Q.sum(P[k].map((p, l) => p * Xh[l][j]))))));
    const nus = LA.eighReal(M).values.map((v) => Math.sqrt(Math.max(0.25, v)));
    const S = Q.sum(nus.map((nu) => (nu > 0.5 + 1e-12 ? (nu + 0.5) * Math.log(nu + 0.5) - (nu - 0.5) * Math.log(nu - 0.5) : 0)));
    return { S, nus };
  }

  const api = {
    PAULI, pauliString, pauliLabels, pauliCommute, generateAlgebra, commutant, dimOf, intersect, inSpan, analyseAlgebra, siteAlgebraGenerators, localityCheck,
    cyclicSeparating, tomita, modularFlow, kmsCheck, blochVector, qubitState, typeITraces, dyadicTraces, arakiWoodsLogSpectrum, TYPE_INFO,
    diamond, diamondRelation, baseSites, inWedge, boost, modularBoost, chainEntanglement,
  };
  Q.aqft = api;
  return api;
});
