/* Connes QFT laboratory: the Connes–Kreimer Hopf algebra and Birkhoff decomposition.
 *
 * Graph side: the commutative algebra 𝓗 freely generated by 1PI QED graphs with a divergent residue,
 * product = disjoint union, coproduct
 *     ΔΓ = Γ⊗1 + 1⊗Γ + ∑_{γ⊊Γ} γ ⊗ Γ/γ,
 * the sum over nonempty products γ of vertex-disjoint divergent proper 1PI subgraphs; antipode
 * S(Γ) = −Γ − ∑ S(γ)(Γ/γ). Elements are Maps from a monomial key (sorted canonical graph keys
 * joined by "·"; "" is 1) to rational coefficients.
 *
 * Tree side: the Hopf algebra of rooted trees 𝓗_R with admissible cuts, and the iterated-integral
 * toy Feynman rules φ(T)(ε) = e^{−|T|εL} / (T! ε^{|T|}) (L = log μ), used in Connes–Kreimer and in
 * Kreimer's work as the model character; graphs are sent to trees by their nesting forests.
 *
 * Characters take values in Laurent series (laurent.js). The Birkhoff decomposition is the
 * Connes–Kreimer recursion
 *     φ₋(Γ) = −T[φ(Γ) + ∑ φ₋(γ) φ(Γ/γ)],   φ₊(Γ) = (1 − T)[φ(Γ) + ∑ φ₋(γ) φ(Γ/γ)],
 * with T the pole-part projection, so φ = φ₋^{⋆−1} ⋆ φ₊ and the renormalized value is φ₊(Γ)(0).
 */
(function (factory) {
  if (typeof module === "object" && module.exports) module.exports = factory(require("./core.js"), require("./graphs.js"), require("./laurent.js"));
  else factory(self.ConnesQFT, self.ConnesQFT.graphs, self.ConnesQFT.laurent);
})(function (Q, G, LS) {
  "use strict";

  /* ---------- graph registry ---------- */
  const REG = new Map(); // canonical key → graph
  function keyOf(g) {
    if (g.__key) return g.__key;
    const k = G.canonicalKey(g);
    Object.defineProperty(g, "__key", { value: k, enumerable: false });
    if (!REG.has(k)) REG.set(k, g);
    return k;
  }
  const graphOf = (k) => REG.get(k);
  const mono = (keys) => keys.slice().sort().join("·");
  const factors = (m) => (m === "" ? [] : m.split("·"));

  /* ---------- polynomial elements ---------- */
  const el = (pairs = []) => { const m = new Map(); for (const [k, c] of pairs) addTo(m, k, c); return m; };
  function addTo(m, k, c) { const v = (m.get(k) || 0) + c; if (Math.abs(v) < 1e-12) m.delete(k); else m.set(k, v); return m; }
  const elAdd = (a, b, s = 1) => { const m = new Map(a); for (const [k, c] of b) addTo(m, k, s * c); return m; };
  function elMul(a, b) { const m = new Map(); for (const [k1, c1] of a) for (const [k2, c2] of b) addTo(m, mono([...factors(k1), ...factors(k2)]), c1 * c2); return m; }
  const ONE = () => el([["", 1]]);
  const gen = (g) => el([[keyOf(g), 1]]);

  /* ---------- coproduct on graphs ---------- */
  const CO_CACHE = new Map();
  /* Terms of the reduced coproduct ∑ γ ⊗ Γ/γ, each { parts: [subgraph info], left: [graph], right: graph }. */
  function coproductTerms(g) {
    const k = keyOf(g);
    if (CO_CACHE.has(k)) return CO_CACHE.get(k);
    const div = G.divergentSubgraphs(g);
    const terms = [];
    const n = div.length;
    for (let mask = 1; mask < 1 << n; mask++) {
      const parts = div.filter((_, i) => mask & (1 << i));
      let ok = true;
      for (let i = 0; i < parts.length && ok; i++) for (let j = i + 1; j < parts.length && ok; j++) if (G.relation(parts[i], parts[j]) !== "disjoint") ok = false;
      if (!ok) continue;
      const left = parts.map((s) => subgraphAsGraph(g, s));
      const right = G.contract(g, parts);
      right.name = `${g.name} / ${parts.map((s) => s.residue.name).join(" · ")}`;
      left.forEach(keyOf); keyOf(right);
      terms.push({ parts, left, right });
    }
    CO_CACHE.set(k, terms);
    return terms;
  }
  /* A subgraph γ as a graph in its own right, with its external legs restored as stubs. */
  function subgraphAsGraph(g, s) {
    const es = new Set(s.edges), vs = new Set(s.vertices);
    const vertices = g.vertices.filter((v) => vs.has(v.id)).map((v) => ({ ...v }));
    const edges = g.edges.filter((e) => es.has(e.id)).map((e) => ({ ...e }));
    let n = 0;
    for (const e of g.edges) {
      if (es.has(e.id)) continue;
      for (const end of ["a", "b"]) {
        if (!vs.has(e[end])) continue;
        const v = G.vByID(g, e[end]), other = e[end === "a" ? "b" : "a"];
        const o = g.vertices.find((u) => u.id === other);
        const dx = o ? o.x - v.x : 10, dy = o ? o.y - v.y : 0, len = Math.hypot(dx, dy) || 1;
        const xid = `x${n++}`;
        vertices.push({ id: xid, x: v.x + (16 * dx) / len, y: v.y + (16 * dy) / len, kind: "ext" });
        edges.push({ ...e, id: `${e.id}~${end}`, a: end === "a" ? v.id : xid, b: end === "a" ? xid : v.id, bend: 0 });
      }
    }
    return { id: `${g.id}[${s.edges.join(",")}]`, name: s.residue.name, vertices, edges, residue: s.residue.id };
  }
  /* Full coproduct as a list of { left: monomial key, right: key, coef }. */
  function coproduct(g) {
    const k = keyOf(g);
    const out = [{ left: k, right: "", coef: 1, kind: "Γ⊗1" }, { left: "", right: k, coef: 1, kind: "1⊗Γ" }];
    for (const t of coproductTerms(g)) out.push({ left: mono(t.left.map(keyOf)), right: keyOf(t.right), coef: 1, kind: "γ⊗Γ/γ", term: t });
    return out;
  }
  /* Antipode S(Γ) = −Γ − ∑ S(γ)·(Γ/γ), multiplicative on products. */
  const S_CACHE = new Map();
  function antipode(g) {
    const k = keyOf(g);
    if (S_CACHE.has(k)) return S_CACHE.get(k);
    let s = el([[k, -1]]);
    for (const t of coproductTerms(g)) {
      const Sg = t.left.reduce((acc, h) => elMul(acc, antipode(h)), ONE());
      s = elAdd(s, elMul(Sg, gen(t.right)), -1);
    }
    S_CACHE.set(k, s);
    return s;
  }
  const antipodeMono = (m) => factors(m).reduce((acc, k) => elMul(acc, antipode(graphOf(k))), ONE());
  /* Check m(S ⊗ id)Δ(Γ) = 0 for a graph (the counit vanishes on Γ). */
  function antipodeCheck(g) {
    let acc = new Map();
    for (const t of coproduct(g)) acc = elAdd(acc, elMul(antipodeMono(t.left), t.right === "" ? ONE() : gen(graphOf(t.right))));
    return acc;
  }

  /* ---------- forests ---------- */
  /* Zimmermann forests: sets of divergent proper subgraphs, pairwise nested or disjoint (never overlapping). */
  function forests(g) {
    const div = G.divergentSubgraphs(g);
    const out = [];
    for (let mask = 0; mask < 1 << div.length; mask++) {
      const fs = div.filter((_, i) => mask & (1 << i));
      let ok = true;
      for (let i = 0; i < fs.length && ok; i++) for (let j = i + 1; j < fs.length && ok; j++) if (G.relation(fs[i], fs[j]) === "overlap") ok = false;
      if (ok) out.push(fs);
    }
    return { subgraphs: div, forests: out };
  }
  /* Is a selection of subgraphs (by index in the divergent list) a legal forest? Names the offending pair. */
  function checkForest(g, indices) {
    const div = G.divergentSubgraphs(g);
    for (let i = 0; i < indices.length; i++) for (let j = i + 1; j < indices.length; j++) {
      if (G.relation(div[indices[i]], div[indices[j]]) === "overlap") return { ok: false, pair: [indices[i], indices[j]] };
    }
    return { ok: true };
  }
  /* Maximal forests (each extended by Γ itself) as rooted trees: a node per subgraph, children = maximal proper sub-elements. */
  function maximalForests(g) {
    const { forests: fs } = forests(g);
    const sets = fs.map((f) => f.map((s) => s.edges.join(",")));
    return fs.filter((f, i) => !sets.some((t, j) => j !== i && t.length > sets[i].length && sets[i].every((x) => t.includes(x))));
  }
  function forestTree(g, forest) {
    const nodes = G.containmentTree(g, forest);
    const build = (idx) => nodes.filter((n) => n.parent === idx).map((n) => build(n.index));
    const root = nodes.findIndex((n) => n.whole);
    return build(root);
  }

  /* ---------- rooted trees ---------- */
  /* A tree is its list of child subtrees; canonical string "[" + sorted children + "]"; • is "[]". */
  const tkey = (t) => `[${t.map(tkey).sort().join("")}]`;
  function parseTree(s) {
    let i = 0;
    const rec = () => { if (s[i] !== "[") throw new Error(`bad tree ${s}`); i++; const ch = []; while (s[i] === "[") ch.push(rec()); if (s[i] !== "]") throw new Error(`bad tree ${s}`); i++; return ch; };
    const t = rec();
    return t;
  }
  const tsize = (t) => 1 + Q.sum(t.map(tsize));
  const tfactorial = (t) => tsize(t) * t.reduce((p, c) => p * tfactorial(c), 1);
  const tdepth = (t) => 1 + Math.max(0, ...t.map(tdepth));
  /* Coproduct on 𝓗_R by Δ(B₊(T₁⋯T_k)) = B₊(T₁⋯T_k)⊗1 + (id ⊗ B₊)Δ(T₁⋯T_k). Returns a Map "leftMono|right" → coef with monomials of tree keys. */
  function treeCoproduct(t) {
    // Δ of the forest of children, multiplicatively
    let acc = new Map([["|", 1]]); // "" ⊗ ""
    for (const c of t) {
      const dc = treeCoproduct(c);
      const next = new Map();
      for (const [k1, c1] of acc) for (const [k2, c2] of dc) {
        const [l1, r1] = k1.split("|"), [l2, r2] = k2.split("|");
        const key = `${mono([...factors(l1), ...factors(l2)])}|${mono([...factors(r1), ...factors(r2)])}`;
        next.set(key, (next.get(key) || 0) + c1 * c2);
      }
      acc = next;
    }
    // (id ⊗ B₊): graft the right factors under a new root
    const out = new Map([[`${tkey(t)}|`, 1]]);
    for (const [k, c] of acc) {
      const [l, r] = k.split("|");
      const rt = tkey(factors(r).map(parseTree));
      const key = `${l}|${rt}`;
      out.set(key, (out.get(key) || 0) + c);
    }
    return out;
  }
  /* τ: graph → sum of trees over its maximal forests (the nesting structure of its subdivergences). */
  function graphToTrees(g) {
    const m = new Map();
    for (const f of maximalForests(g)) { const k = tkey(forestTree(g, f)); m.set(k, (m.get(k) || 0) + 1); }
    return m;
  }
  /* Check that τ is a coalgebra map on Γ: Δ_R(τΓ) = (τ⊗τ)ΔΓ. Returns the two sides as Maps. */
  function treeMapCheck(g) {
    const lhs = new Map();
    for (const [t, c] of graphToTrees(g)) for (const [k, v] of treeCoproduct(parseTree(t))) lhs.set(k, (lhs.get(k) || 0) + c * v);
    const rhs = new Map();
    const tauMono = (m) => factors(m).reduce((acc, gk) => {
      const tg = graphToTrees(graphOf(gk));
      const next = new Map();
      for (const [a, ca] of acc) for (const [b, cb] of tg) { const key = mono([...factors(a), b]); next.set(key, (next.get(key) || 0) + ca * cb); }
      return next;
    }, new Map([["", 1]]));
    for (const term of coproduct(g)) {
      const L = tauMono(term.left), R = tauMono(term.right);
      for (const [a, ca] of L) for (const [b, cb] of R) { const key = `${a}|${b}`; rhs.set(key, (rhs.get(key) || 0) + ca * cb); }
    }
    return { lhs, rhs };
  }

  /* ---------- characters ---------- */
  /* Toy Feynman rule on a tree: φ(T)(ε) = e^{−|T| ε L} / (T! ε^{|T|}), as a Laurent series to order hi. */
  function toyTree(t, L, hi) {
    const n = tsize(t);
    const ex = LS.exp(LS.make(0, [0, -n * L], hi + n));
    return LS.truncate(LS.mul(LS.monomial(-n, 1 / tfactorial(t)), ex), hi);
  }
  /* A character on graphs from a rule on generators; multiplicative on monomials, φ(1) = 1. */
  function character(rule, hi) {
    const cache = new Map();
    const onKey = (k) => { if (!cache.has(k)) cache.set(k, LS.truncate(rule(graphOf(k)), hi)); return cache.get(k); };
    const onMono = (m) => factors(m).reduce((acc, k) => LS.mul(acc, onKey(k)), LS.constant(1, Infinity));
    return { onKey, onMono, hi };
  }
  /* The toy character φ = φ_tree ∘ τ at scale L = log μ. */
  function toyCharacter(L, hi = 6) {
    return character((g) => { let s = LS.zero(hi); for (const [t, c] of graphToTrees(g)) s = LS.add(s, LS.scale(toyTree(parseTree(t), L, hi), c)); return s; }, hi);
  }
  /* Convolution (φ ⋆ ψ)(Γ) = m(φ ⊗ ψ)ΔΓ, with each term reported. */
  function convolve(phi, psi, g) {
    const terms = coproduct(g).map((t) => ({ ...t, value: LS.mul(phi.onMono(t.left), psi.onMono(t.right)) }));
    return { terms, total: terms.reduce((s, t) => LS.add(s, t.value), LS.zero(Math.min(phi.hi, psi.hi))) };
  }
  /* Birkhoff decomposition by the Connes–Kreimer recursion. Returns φ₋, φ₊ as character-like objects with a trace of each step. */
  function birkhoff(phi) {
    const minus = new Map(), plus = new Map(), steps = new Map();
    const minusKey = (k) => {
      if (minus.has(k)) return minus.get(k);
      const g = graphOf(k);
      let bar = phi.onKey(k);
      const parts = [];
      for (const t of coproductTerms(g)) {
        const pm = t.left.reduce((acc, h) => LS.mul(acc, minusKey(keyOf(h))), LS.constant(1, Infinity));
        const contrib = LS.mul(pm, phi.onKey(keyOf(t.right)));
        parts.push({ term: t, counterterm: pm, value: contrib });
        bar = LS.add(bar, contrib);
      }
      bar = LS.clean(bar);
      const m = LS.neg(LS.pole(bar)), p = LS.regular(bar);
      minus.set(k, m); plus.set(k, p); steps.set(k, { bar, parts });
      return m;
    };
    const minusMono = (m) => factors(m).reduce((acc, k) => LS.mul(acc, minusKey(k)), LS.constant(1, Infinity));
    const plusKey = (k) => { minusKey(k); return plus.get(k); };
    const plusMono = (m) => factors(m).reduce((acc, k) => LS.mul(acc, plusKey(k)), LS.constant(1, Infinity));
    return {
      minus: { onKey: minusKey, onMono: minusMono, hi: Infinity },
      plus: { onKey: plusKey, onMono: plusMono, hi: phi.hi },
      steps: (k) => { minusKey(k); return steps.get(k); },
      renormalized: (k) => LS.at0(plusKey(k)),
    };
  }
  /* φ ∘ S (the convolution inverse of a character) on a graph. */
  function inverseCharacter(phi) {
    const onKey = (k) => { let s = LS.zero(phi.hi); for (const [m, c] of antipode(graphOf(k))) s = LS.add(s, LS.scale(phi.onMono(m), c)); return s; };
    return { onKey, onMono: (m) => factors(m).reduce((acc, k) => LS.mul(acc, onKey(k)), LS.constant(1, Infinity)), hi: phi.hi };
  }

  /* ---------- formal diffeomorphisms ---------- */
  /* Compose formal series f(g) = g + a₂g² + … and h, both given by coefficient lists [1, a₂, a₃, …] (index k ↔ g^{k+1}), to order n. */
  function composeSeries(f, h, n = Math.min(f.length, h.length)) {
    // (f ∘ h)(g) = ∑ f_k h(g)^{k+1}
    const mulS = (a, b) => { const c = new Array(n).fill(0); for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) if (i + j + 1 < n) c[i + j + 1] += a[i] * b[j]; return c; };
    // represent series as coefficients of g^{1..n}: array index k ↔ g^{k+1}
    let pow = h.slice(0, n), out = new Array(n).fill(0);
    for (let k = 0; k < n; k++) { for (let i = 0; i < n; i++) out[i] += (f[k] || 0) * pow[i]; pow = mulS(pow, h); }
    return out;
  }
  const evalSeries = (f, g) => f.reduce((s, a, k) => s + a * Math.pow(g, k + 1), 0);

  /* ---------- Riemann sphere: the loop γ(ε) on a circle about ε = 0 ---------- */
  function complexEval(series, z) {
    let re = 0, im = 0;
    series.c.forEach((a, i) => { const k = series.lo + i; const r = Math.pow(Math.hypot(z[0], z[1]), k), th = k * Math.atan2(z[1], z[0]); re += a * r * Math.cos(th); im += a * r * Math.sin(th); });
    return [re, im];
  }
  /* Sample a one-generator loop γ(ε) = φ(Γ)(ε) and its Birkhoff factors on |ε| = r: γ = −γ₋ + γ₊ in the additive group of a primitive. */
  function loopOnCircle(series, r, n = 120) {
    const minus = LS.neg(LS.pole(series)), plus = LS.regular(series);
    return Q.range(n + 1).map((i) => { const th = (2 * Math.PI * i) / n, z = [r * Math.cos(th), r * Math.sin(th)]; return { theta: th, z, gamma: complexEval(series, z), minus: complexEval(minus, z), plus: complexEval(plus, z) }; });
  }

  const api = {
    REG, keyOf, graphOf, mono, factors, el, elAdd, elMul, ONE, gen, coproductTerms, subgraphAsGraph, coproduct, antipode, antipodeMono, antipodeCheck,
    forests, checkForest, maximalForests, forestTree, tkey, parseTree, tsize, tfactorial, tdepth, treeCoproduct, graphToTrees, treeMapCheck,
    toyTree, character, toyCharacter, convolve, birkhoff, inverseCharacter, composeSeries, evalSeries, complexEval, loopOnCircle,
  };
  Q.hopf = api;
  return api;
});
