/* Operator-algebraic track (spec §74–§90, §122, §133). Finite matrix algebras are type I and are
   used only as surrogates; type III enters through modular data and cited theorems. */

/* Bloch-sphere projection of a 3-vector. */
function bloch(cx, cy, R, pts, { cls = "aqft", head = null, axes = true } = {}) {
  const P = (v) => [cx + R * (v[0] * 0.95 - v[1] * 0.35), cy - R * (v[2] * 0.9 - v[1] * 0.25)];
  let s = circ(cx, cy, R, "", 'fill="none" stroke="var(--rule)"') + `<ellipse cx="${cx}" cy="${cy}" rx="${R}" ry="${R * 0.3}" fill="none" stroke="var(--rule)" stroke-dasharray="3 3"/>`;
  if (axes) s += arrow(cx, cy, ...P([0, 0, 1.15]), "axis") + txt(...P([0, 0, 1.25]), "z", "xs serif") + arrow(cx, cy, ...P([1.2, 0, 0]), "axis") + txt(...P([1.3, 0, 0]), "x", "xs serif");
  if (pts.length) s += path(pathD(pts.map(P)), cls, 'fill="none" stroke-width="2"');
  if (head) s += arrow(cx, cy, ...P(head), cls) + circ(...P(head), 4, `f${cls}`);
  return s;
}
const PAULI2 = AQ.pauliLabels(2);
const ALG_PRESETS = { "M₂ ⊗ 1": ["XI", "ZI"], "abelian ⟨Z ⊗ 1⟩": ["ZI"], "⟨Z⊗Z, X⊗X⟩": ["ZZ", "XX"], "⟨X⊗X, Z⊗I⟩": ["XX", "ZI"], "M₄ (everything)": ["XI", "ZI", "IX", "IZ"] };

/* ---------- §74–75 from matrices to von Neumann algebras ---------- */
scene({
  id: "matrices", track: "aqft", title: "From matrices to von Neumann algebras", sections: [74, 75],
  summary: "Ordinary quantum mechanics: observables A ∈ B(ℋ), for a finite system the matrices M_n(ℂ) acting on state vectors. Increase the degrees of freedom; take bounded operators, close in the weak topology: a von Neumann algebra, characterised by M = M″.",
  refs: ["mvn1936", "br1987", "haag"],
  init: () => ({ k: 2, th: 0.7 }),
  anim: ["field"],
  controls: (c) => `${slider("k", "number of qubits", 1, 8, 1, c.s.k, (v) => String(v))} ${slider("th", "rotation angle of the observable", 0, 3.14, 0.01, c.s.th, (v) => v.toFixed(2))}`,
  panels: {
    field: (c) => {
      // a Hermitian observable acting on a qubit state: e^{-iθ X/2} rotates the Bloch vector
      const tt = c.t % (2 * PI);
      const U = LA.expiH(AQ.PAULI.X, c.s.th / 2);
      const psi0 = [[1, 0], [0, 0]];
      const traj = Q.linspace(0, c.s.th, 40).map((th) => { const V = LA.expiH(AQ.PAULI.X, th / 2); const ps = LA.matvec(V, psi0); const rho = LA.from([[LA.C.mul(ps[0], LA.C.conj(ps[0])), LA.C.mul(ps[0], LA.C.conj(ps[1]))], [LA.C.mul(ps[1], LA.C.conj(ps[0])), LA.C.mul(ps[1], LA.C.conj(ps[1]))]]); return AQ.blochVector(LA.scale(rho, 2)); });
      return { title: "A MATRIX ACTING ON A STATE", sub: "M₂(ℂ) on ℂ²", body: svg(400, 200, bloch(200, 100, 75, traj, { head: traj[traj.length - 1] }) + txt(14, 192, `e^{−iθX/2}|0⟩ for θ ∈ [0, ${c.s.th.toFixed(2)}] (t = ${tt.toFixed(1)})`, "xs ink2"), "Bloch sphere"), foot: `‖U − U(θ)‖ check: U is unitary to ${LA.maxAbsDiff(LA.mul(U, LA.adj(U)), LA.eye(2)).toExponential(0)}.` };
    },
    diagram: (c) => ({ title: "MORE DEGREES OF FREEDOM", sub: `${c.s.k} qubits`, body: barChart({ W: 400, H: 190, items: Q.range(8).map((i) => ({ label: `${i + 1}`, value: (i + 1) * Math.log10(4), cls: i + 1 <= c.s.k ? "aqft" : "ncg", tip: `${i + 1} qubits: dimension 4^${i + 1} = ${Math.pow(4, i + 1)}` })), xlabel: "qubits", ylabel: "log₁₀ dim M_{2^k}" }), foot: `dim M₂ ⊗ … ⊗ M₂ (${c.s.k} copies) = ${Math.pow(4, c.s.k)}; a field has infinitely many degrees of freedom in every region.` }),
    algebra: () => ({ title: "THE SEQUENCE", body: `<pre class="small" style="font-family:var(--mono)">finite matrices\n     ↓\nbounded operators B(ℋ)\n     ↓\nweak operator closure\n     ↓\nvon Neumann algebra</pre>${formula("\\mathcal{M} = \\mathcal{M}'',\\qquad \\mathcal{M}' = \\{T : TA = AT\\ \\text{for all}\\ A\\in\\mathcal{M}\\}")}` }),
    space: () => ({ title: "VON NEUMANN'S THEOREM", body: `<p class="small">For a unital *-algebra of bounded operators, the weak closure equals the bicommutant. So "closed in the weak topology" and "M = M″" are the same condition — and the second can be computed: the next view does it for matrix algebras.</p>${sceneLink("commutant", "commutant visualizer")}` }),
  },
  notes: () => `<p>Every finite-dimensional von Neumann algebra is a direct sum of full matrix algebras (type I). The infinite-dimensional ones that local QFT needs are reached by closure; their classification into types is the subject of the following views.</p>`,
});

/* ---------- §76–77 commutant visualizer and factors ---------- */
/* The algebra generated by the chosen Pauli strings (the identity alone when none is chosen). */
function commutantAlgebra(c) {
  const gens = c.s.gens.length ? c.s.gens : ["II"];
  return { gens, a: AQ.analyseAlgebra(gens.map(AQ.pauliString), 4) };
}
scene({
  id: "commutant", track: "aqft", title: "Commutant visualizer and factors", sections: [76, 77],
  summary: "The 16 two-qubit Pauli operators as nodes, joined when they commute. Choose an algebra 𝓜 by its generators: the page computes 𝓜, its commutant 𝓜′ (everything commuting with it), 𝓜″ (closure back to 𝓜) and the centre Z(𝓜) = 𝓜 ∩ 𝓜′. Trivial centre: FACTOR.",
  refs: ["mvn1936", "br1987"],
  init: () => ({ preset: "M₂ ⊗ 1", gens: ["XI", "ZI"], show: "M'" }),
  controls: (c) => `${seg("preset", Object.keys(ALG_PRESETS).map((k) => [k, k]), c.s.preset, "algebra")} ${seg("show", [["M", "𝓜"], ["M'", "𝓜′"], ["M''", "𝓜″"], ["Z", "centre"]], c.s.show, "highlight")}`,
  onSet: (c, key, v) => { if (key === "preset") c.s.gens = ALG_PRESETS[v].slice(); },
  actions: { gen: (c, arg) => { c.s.gens = c.s.gens.includes(arg) ? c.s.gens.filter((g) => g !== arg) : [...c.s.gens, arg]; c.s.preset = "custom"; } },
  panels: {
    field: (c) => {
      const { a } = commutantAlgebra(c);
      const set = { M: a.M, "M'": a.Mprime, "M''": a.Mbiprime, Z: a.centre }[c.s.show];
      const R = 95, cx = 200, cy = 115;
      const pos = PAULI2.map((p, i) => [cx + R * Math.cos((2 * PI * i) / 16 - PI / 2), cy + R * Math.sin((2 * PI * i) / 16 - PI / 2)]);
      let s = "";
      PAULI2.forEach((p, i) => PAULI2.forEach((q, j) => { if (j > i && AQ.pauliCommute(p, q) && p !== "II" && q !== "II") s += ln(...pos[i], ...pos[j], "grid", 'stroke-width="0.8"'); }));
      PAULI2.forEach((p, i) => {
        const inSet = AQ.inSpan(set, AQ.pauliString(p)), isGen = c.s.gens.includes(p);
        s += `<g data-act="gen" data-arg="${p}" style="cursor:pointer" data-tip="${p}${isGen ? " (generator)" : ""}${inSet ? `, in ${c.s.show}` : ""}">` + circ(...pos[i], 13, inSet ? "faqft" : "", inSet ? "" : 'fill="var(--panel)" stroke="var(--axis)"') + (isGen ? circ(...pos[i], 16, "", 'fill="none" stroke="var(--ck)" stroke-width="2"') : "") + txt(pos[i][0], pos[i][1] + 3.5, p, "xs mono", `text-anchor="middle" style="${inSet ? "fill:var(--bg)" : ""}"`) + "</g>";
      });
      return { title: "OPERATORS AS NODES", sub: `lines join commuting pairs; filled = in ${c.s.show}`, body: svg(400, 230, s, "Pauli commutation graph"), foot: "Click a node to add or remove it as a generator (orange ring)." };
    },
    algebra: (c) => {
      const { gens, a } = commutantAlgebra(c);
      return { title: "COMPUTED", sub: "on ℂ² ⊗ ℂ²", body: kv([["generators", gens.join(", ")], ["dim 𝓜", String(a.dimM)], ["dim 𝓜′", String(a.dimMprime)], ["dim 𝓜″", String(a.dimMbiprime)], ["𝓜″ = 𝓜", a.bicommutantEqual ? '<span class="pass">yes</span>' : '<span class="fail">no</span>'], ["dim Z(𝓜)", String(a.dimCentre)], ["factor", a.factor ? '<b class="pass">FACTOR: Z(𝓜) = ℂ1</b>' : '<span class="fail">not a factor</span>']]) };
    },
    diagram: (c) => {
      const { a } = commutantAlgebra(c);
      const W = 400, s = `<circle cx="160" cy="95" r="70" class="bgaqft" stroke="var(--aqft)"/><circle cx="240" cy="95" r="70" class="bgncg" stroke="var(--ncg)"/>` + txt(110, 95, `𝓜 (${a.dimM})`, "sm", 'text-anchor="middle"') + txt(290, 95, `𝓜′ (${a.dimMprime})`, "sm", 'text-anchor="middle"') + txt(200, 99, `Z (${a.dimCentre})`, "sm", 'text-anchor="middle" style="font-weight:650"') + txt(200, 184, a.factor ? "overlap = ℂ1 only: a factor" : "a larger overlap: not a factor", "xs ink2", 'text-anchor="middle"');
      return { title: "THE CENTRE AS THE OVERLAP", sub: "Z(𝓜) = 𝓜 ∩ 𝓜′", body: svg(W, 190, s, "centre") };
    },
    space: () => ({ title: "THE RULE", body: `<p class="small">Two Pauli strings commute exactly when they anticommute on an even number of sites; the graph uses this rule and the algebra panel solves ${tex("[A_i, T] = 0")} as a linear system for the commutant.</p>` }),
  },
  notes: () => `<p>${formula("\\mathcal{M}' = \\{T : TA = AT\\ \\forall A\\in\\mathcal{M}\\},\\qquad Z(\\mathcal{M}) = \\mathcal{M}\\cap\\mathcal{M}'")} The commutant is computed as the null space of ${tex("T \\mapsto ([A_i, T])_i")}, the bicommutant by applying the same step again, and the centre by intersecting subspaces. M₂ ⊗ 1 is a factor; the abelian algebra generated by Z ⊗ 1 is not (its centre is itself).</p>`,
});

/* ---------- §78, §90 type I / II / III ---------- */
scene({
  id: "types", track: "aqft", title: "Type I, II and III", sections: [78, 90],
  summary: "Classification through projections, not a table. Type I: minimal projections, the space splits into atoms. Type II: no minimal projections, but a finite trace: continuous divisibility. Type III: no nonzero finite projection — every nonzero piece is as big as the whole. The advanced panel separates III₀, III_λ and III₁ by modular spectral data.",
  refs: ["mvn1936", "connes1973", "powers1967", "arakiwoods1968", "yngvason2005"],
  init: () => ({ type: "I", depth: 2, n: 4, lam: 0.5, lam2: 0.3 }),
  anim: [],
  controls: (c) => `${seg("type", [["I", "Type I"], ["II", "Type II"], ["III", "Type III"]], c.s.type)} ${slider("depth", "subdivide", 0, 6, 1, c.s.depth, (v) => String(v))} ${c.s.type === "I" ? slider("n", "n (M_{n})", 2, 8, 1, c.s.n, (v) => String(v)) : ""}`,
  panels: {
    field: (c) => {
      let s = "";
      const W = 380, x0 = 10;
      if (c.s.type === "I") {
        const n = c.s.n;
        for (let k = 0; k < n; k++) s += rect(x0 + (W * k) / n + 1, 40, W / n - 2, 50, "faqft", `fill-opacity="${0.35 + 0.5 * (k % 2)}" data-tip="minimal projection ${k + 1}: trace 1/${n}"`) + txt(x0 + (W * (k + 0.5)) / n, 70, "atom", "xs", 'text-anchor="middle" style="fill:var(--bg)"');
        s += txt(x0, 116, `ℋ = ℂ^{${n}} splits into ${n} atomic pieces (minimal projections); traces k/${n}.`, "xs ink2") + txt(x0, 132, "An atom cannot be subdivided.", "xs ink2");
      } else if (c.s.type === "II") {
        const m = c.s.depth, N = Math.pow(2, m);
        for (let k = 0; k < N; k++) s += rect(x0 + (W * k) / N + 0.5, 40, Math.max(0.5, W / N - 1), 50, "fncg", `fill-opacity="${0.3 + 0.6 * ((k * 7) % N) / N}" data-tip="projection of trace ${k}/${N}"`);
        s += txt(x0, 116, `every projection halves again (depth ${m}): ${N + 1} dyadic trace values in [0, 1],`, "xs ink2") + txt(x0, 132, "dense in the limit — a finite trace survives", "xs ink2");
      } else {
        // self-similar: each subdivision reveals a copy of the whole
        const draw = (x, w, d) => { s += rect(x, 40 + d * 14, w, 12, "fck", `fill-opacity="${(0.25 + 0.12 * d).toFixed(2)}"`); if (d < Math.min(6, c.s.depth + 1)) { draw(x, w / 2 - 1, d + 1); draw(x + w / 2 + 1, w / 2 - 1, d + 1); } };
        draw(x0, W, 0);
        s += txt(x0, 140, "every nonzero piece is equivalent to the whole (P ∼ 1):", "xs ink2") + txt(x0, 155, "infinitely divisible, and no trace can measure it", "xs ink2");
      }
      return { title: `TYPE ${c.s.type}`, sub: "projections", body: svg(400, 160, s, "projections") };
    },
    diagram: (c) => {
      const tr = c.s.type === "I" ? AQ.typeITraces(c.s.n) : c.s.type === "II" ? AQ.dyadicTraces(c.s.depth) : [];
      return { title: "TRACE VALUES OF PROJECTIONS", sub: c.s.type === "III" ? "none: no semifinite trace" : `${tr.length} values`, body: c.s.type === "III" ? `<p class="small">A type III factor has no faithful normal semifinite trace; only the modular data below tell type III factors apart.</p>` : svg(400, 70, ln(10, 40, 390, 40, "axis") + tr.map((v) => ln(10 + 380 * v, 30, 10 + 380 * v, 50, c.s.type === "I" ? "aqft" : "ncg", `stroke-width="2" data-tip="trace ${fmt(v, 4)}"`)).join("") + txt(10, 64, "0", "xs mut") + txt(390, 64, "1", "xs mut", 'text-anchor="end"'), "trace values") };
    },
    algebra: (c) => {
      const L1 = AQ.arakiWoodsLogSpectrum([c.s.lam, c.s.lam, c.s.lam, c.s.lam]);
      const L2 = AQ.arakiWoodsLogSpectrum([c.s.lam, c.s.lam2, c.s.lam, c.s.lam2]);
      const row = (Ls, y, cls) => Ls.filter((x) => Math.abs(x) < 4).map((x) => circ(200 + x * 45, y, 2.5, `f${cls}`, `data-tip="log of a Δ eigenvalue: ${fmt(x, 4)}"`)).join("");
      const s = ln(20, 40, 380, 40, "axis") + row(L1, 40, "aqft") + txt(20, 28, `III_λ: Powers state, λ = ${c.s.lam} — log-spectrum λ^{ℤ} (evenly spaced)`, "xs ink2") + ln(20, 100, 380, 100, "axis") + row(L2, 100, "ck") + txt(20, 88, `III₁: λ₁ = ${c.s.lam}, λ₂ = ${c.s.lam2}, log ratio irrational — filling ℝ`, "xs ink2") + txt(20, 140, "III₀: S(M) = {0, 1} (not drawn)", "xs ink2");
      return { title: G.advanced ? "CONNES CLASSIFICATION (ADVANCED)" : "MODULAR SPECTRA", sub: "finite truncations of Araki–Woods products", body: svg(400, 150, s, "modular spectra"), foot: "Connes' invariant S(M) = ∩ Spec(Δ_{φ}): {0} ∪ λ^{ℤ} for III_{λ}, [0, ∞) for III₁. Type III₁ is the case of local relativistic QFT." };
    },
    space: () => ({ title: "TABLE (FOR REFERENCE)", body: table(["type", "projections", "trace"], AQ.TYPE_INFO.map((t) => [t.name, esc(t.projections), esc(t.trace)])) }),
  },
  details: () => `<p>Murray and von Neumann: a factor is type I if it has a minimal projection, type II if it has none but has nonzero finite projections, type III if every nonzero projection is properly infinite (equivalent to 1). Connes (1973) subdivides type III by the invariant S(M), the intersection over faithful normal states of the spectra of the modular operators: S = {0, 1} (III₀), {0} ∪ λ^ℤ for 0 &lt; λ &lt; 1 (III_λ), [0, ∞) (III₁). The finite truncations drawn here only approximate these spectra; a finite matrix algebra is always type I. Type III is not "infinite-dimensional matrices": B(ℋ) for infinite-dimensional ℋ is type I.</p>`,
  notes: () => `<p>Classify by what projections can do. In finite quantum mechanics every subspace splits into rank-one atoms (type I). In type II the splitting never ends but a trace still measures sizes. In type III even that fails, and the only invariants are modular. ${sceneLink("why3", "why local QFT lands in type III")}</p>`,
});

/* ---------- §79, §88, §89 why QFT leads to type III; entanglement ---------- */
scene({
  id: "why3", track: "aqft", title: "Why local QFT leads to type III", sections: [79, 88, 89],
  summary: "A bounded region 𝒪 ↦ 𝒜(𝒪). As spatial resolution increases the region holds arbitrarily many field degrees of freedom, and modes straddle its boundary at every shorter scale. The computed vacuum entanglement of a block keeps growing as the lattice spacing shrinks — the UV origin of the type III structure.",
  refs: ["yngvason2005", "bdf1987", "witten2018", "calabrese2004", "casini2009", "peschel2003"],
  init: () => ({ level: 2 }),
  controls: (c) => slider("level", "resolution (halvings of the spacing)", 0, 3, 1, c.s.level, (v) => `a = 1/${Math.pow(2, v)}`),
  panels: {
    space: (c) => {
      const n = 4 * Math.pow(2, c.s.level);
      let s = poly([[200, 20], [320, 120], [200, 220], [80, 120]], "bgaqft", 'stroke="var(--aqft)" stroke-width="1.5"');
      for (let i = 0; i < n; i++) { const x = 80 + (240 * (i + 0.5)) / n; s += circ(x, 120, Math.max(1, 6 - c.s.level), "faqft"); }
      s += txt(200, 240, `${n} lattice sites in the base of 𝒪 → ∞ as a → 0`, "xs ink2", 'text-anchor="middle"');
      return { title: "A BOUNDED REGION", sub: "degrees of freedom inside", body: svg(400, 248, s, "region") };
    },
    field: (c) => {
      let s = ln(200, 10, 200, 190, "ck", 'stroke-width="2"') + txt(206, 20, "boundary", "xs ink2");
      for (let L = 0; L <= c.s.level + 1; L++) { const w = 160 / Math.pow(2, L); const n = Math.pow(2, L); for (let k = 0; k < n; k++) { const y = 30 + L * 34 + (k % 2) * 4; s += path(pathD(Q.linspace(-1, 1, 40).map((u) => [200 + u * w, y + 10 * Math.sin(PI * (u + 1)) * Math.cos(k)])), "aqft", 'fill="none" opacity="0.7"'); } }
      s += txt(14, 194, "coarse scale: few correlations · finer: more boundary-crossing modes · UV: arbitrarily fine", "xs ink2");
      return { title: "MODES STRADDLING THE BOUNDARY", sub: "shorter and shorter scales", body: svg(400, 200, s, "boundary modes") };
    },
    diagram: (c) => {
      const pts = Q.range(4).map((l) => { const N = 10 * Math.pow(2, l); return [l, AQ.chainEntanglement(N, N / 2, 1e-3).S]; });
      return { title: "VACUUM ENTANGLEMENT OF A BLOCK", sub: "harmonic chain, computed", body: lineChart({ W: 400, H: 200, xr: [0, 3], yr: [0, 1.4], series: [{ pts, cls: "aqft", label: "S(block)" }, { pts: pts.map(([l]) => [l, pts[0][1] + (l * Math.log(2)) / 3]), cls: "ck", label: "+ (1/3) log 2 per halving", dash: "4 3" }], points: [{ x: c.s.level, y: pts[c.s.level][1], cls: "faqft" }], xlabel: "halvings of the lattice spacing" }), foot: "S grows like (c/3) log(ℓ/a) with c = 1 (Calabrese–Cardy) and never saturates as a → 0." };
    },
    algebra: () => ({ title: "WHAT IS (AND IS NOT) PROVEN", body: `<ul class="small"><li>In relativistic QFT, local algebras of bounded regions are generically type III (Araki; Haag).</li><li>Under standard conditions (e.g. nuclearity, scaling limits) they are isomorphic to the hyperfinite III₁ factor (Buchholz–D'Antoni–Fredenhagen 1987; review: Yngvason 2005), using Connes' classification.</li><li>Not claimed: that every local algebra of every QFT is the same factor without hypotheses.</li></ul><p class="small"><b>Entanglement warning.</b> A finite bipartite system splits as ℋ_A ⊗ ℋ_B; local relativistic QFT does not: the naive type I tensor-factor picture is not its local structure.</p>` }),
  },
  notes: () => `<p>Finite quantum mechanics has finitely many degrees of freedom in a box and type I algebras. A relativistic field has infinitely many in every region, and the vacuum entangles them across every boundary at every scale; the harmonic-chain calculation (Peschel's correlation-matrix method) shows the entropy diverging logarithmically as the cutoff is removed. That divergence is one face of the type III structure.</p>`,
});

/* ---------- §80–82 Haag–Kastler net, locality, isotony ---------- */
const NET_K = 9;
scene({
  id: "net", track: "aqft", title: "Haag–Kastler net: locality and isotony", sections: [80, 81, 82],
  summary: "Nested spacetime diamonds give nested algebras, 𝒪₁ ⊂ 𝒪₂ ⇒ 𝒜(𝒪₁) ⊂ 𝒜(𝒪₂); spacelike diamonds give commuting algebras, [A, B] = 0. Drag the diamonds: the algebra boxes nest, separate and commute in step. The algebra side is a finite chain of qubits standing in for the field.",
  refs: ["hk1964", "haag", "fewster2020"],
  init: () => ({ d1: [0, -0.4, 0.6], d2: [0, 0.2, 1.6] }),
  controls: (c) => `${slider("r1", "radius of 𝒪₁", 0.3, 2, 0.05, c.s.d1[2], (v) => v.toFixed(2))} ${slider("r2", "radius of 𝒪₂", 0.3, 2, 0.05, c.s.d2[2], (v) => v.toFixed(2))} <span class="small muted">drag the diamond centres</span>`,
  onSet: (c, key, v) => { if (key === "r1") c.s.d1 = [c.s.d1[0], c.s.d1[1], v]; if (key === "r2") c.s.d2 = [c.s.d2[0], c.s.d2[1], v]; },
  panels: {
    space: (c) => {
      const M = minkowski({ W: 400, H: 250, scale: 45, cone: false });
      let s = M.s;
      const dia = (d, cls, name, drag) => { const [t, x, r] = d; const pts = [M.P(t + r, x), M.P(t, x + r), M.P(t - r, x), M.P(t, x - r)]; return poly(pts, `bg${cls}`, `stroke="var(--${cls})" stroke-width="1.6" data-link="${name}"`) + circ(...M.P(t, x), 6, `f${cls}`, `data-drag="${drag}" data-tip="drag ${name}"`) + txt(M.P(t + r, x)[0], M.P(t + r, x)[1] - 4, name, "sm", 'text-anchor="middle"'); };
      s += dia(c.s.d2, "ncg", "𝒪₂", "d2") + dia(c.s.d1, "aqft", "𝒪₁", "d1");
      for (let k = 0; k < NET_K; k++) { const x = (k - (NET_K - 1) / 2) * 0.5; s += circ(...M.P(0, x), 2, "vtx", `data-tip="lattice site ${k + 1}"`); }
      const rel = AQ.diamondRelation(AQ.diamond(...c.s.d1), AQ.diamond(...c.s.d2));
      return { title: "REGIONS (1+1 MINKOWSKI)", sub: `𝒪₁ ${rel === "inside" ? "⊂" : rel === "contains" ? "⊃" : rel === "spacelike" ? "⊥ (spacelike)" : rel === "overlap" ? "overlaps" : "causally related to"} 𝒪₂`, body: svg(400, 250, s, "diamonds") };
    },
    algebra: (c) => {
      const D1 = AQ.diamond(...c.s.d1), D2 = AQ.diamond(...c.s.d2), rel = AQ.diamondRelation(D1, D2);
      const s1 = AQ.baseSites(D1, NET_K, 0.5), s2 = AQ.baseSites(D2, NET_K, 0.5);
      // locality on the t = 0 lattice, by the Pauli rule on generators X_k, Z_k
      const gen = (sites) => sites.flatMap((k) => ["X", "Z"].map((P) => Q.range(NET_K).map((i) => (i === k ? P : "I")).join("")));
      const g1 = gen(s1), g2 = gen(s2);
      const allCommute = g1.every((a) => g2.every((b) => AQ.pauliCommute(a, b)));
      const W = 400, H = 200;
      let s = "";
      if (rel === "inside" || rel === "contains") {
        const [inner, outer, ni, no] = rel === "inside" ? [s1, s2, "𝒜(𝒪₁)", "𝒜(𝒪₂)"] : [s2, s1, "𝒜(𝒪₂)", "𝒜(𝒪₁)"];
        s += rect(40, 20, 320, 150, rel === "inside" ? "bgncg" : "bgaqft", 'stroke="var(--axis)" rx="8"') + txt(52, 40, `${no} = M₂ ⊗ … ⊗ M₂ (${outer.length} sites)`, "sm") + rect(110, 70, 180, 80, rel === "inside" ? "bgaqft" : "bgncg", 'stroke="var(--axis)" rx="8"') + txt(122, 92, `${ni} = (${inner.length} sites) ⊗ 1`, "sm") + txt(200, 190, "isotony: the boxes nest", "xs ink2", 'text-anchor="middle"');
      } else {
        s += rect(20, 40, 160, 110, "bgaqft", 'stroke="var(--axis)" rx="8"') + txt(30, 60, `𝒜(𝒪₁): ${s1.length} sites`, "sm") + rect(220, 40, 160, 110, "bgncg", 'stroke="var(--axis)" rx="8"') + txt(230, 60, `𝒜(𝒪₂): ${s2.length} sites`, "sm");
        s += txt(200, 175, rel === "spacelike" ? (allCommute ? "[A, B] = 0 for every pair: locality" : "spacelike but sharing sites?") : `${rel}: generators share sites, some commutators ≠ 0`, "sm", `text-anchor="middle" style="fill:${rel === "spacelike" && allCommute ? "var(--ok)" : "var(--bad)"}"`);
      }
      return { title: "ALGEBRAS", sub: "finite surrogate: qubit chain at t = 0", body: svg(W, H, s, "algebra boxes"), foot: `sites in 𝒪₁: {${s1.map((k) => k + 1).join(", ")}}; in 𝒪₂: {${s2.map((k) => k + 1).join(", ")}}; all generator pairs commute: ${allCommute ? "yes" : "no"}.` };
    },
    field: () => ({ title: "GEOMETRY ↔ ALGEBRA", body: table(["GEOMETRY", "ALGEBRA"], [["regions and inclusion", "observable algebras and inclusion"], ["𝒪₁ ⊂ 𝒪₂", "𝒜(𝒪₁) ⊂ 𝒜(𝒪₂)"], ["𝒪₁ ⊥ 𝒪₂ (spacelike)", "[𝒜(𝒪₁), 𝒜(𝒪₂)] = 0"]]) }),
    diagram: () => ({ title: "THE FINITE SURROGATE", body: `<p class="small">Diamonds centred on t = 0 are matched with the lattice sites of their base. A finite chain gives type I algebras (tensor products of M₂); it reproduces isotony and locality exactly, but not the type III nature of the continuum net. Diamonds moved off t = 0 are classified geometrically only.</p>` }),
  },
  drag: {
    d1: (c, p) => { c.s.d1 = [clamp(-(p.y - 135) / 45, -2, 2), clamp((p.x - 200) / 45, -3.5, 3.5), c.s.d1[2]]; },
    d2: (c, p) => { c.s.d2 = [clamp(-(p.y - 135) / 45, -2, 2), clamp((p.x - 200) / 45, -3.5, 3.5), c.s.d2[2]]; },
  },
  notes: () => `<p>A Haag–Kastler net assigns to each bounded region a von Neumann algebra, with isotony (bigger region, bigger algebra) and Einstein causality (spacelike regions commute). The diamond relation is computed in light-cone coordinates; locality on the lattice by the Pauli commutation rule. Drag 𝒪₁ entirely inside 𝒪₂ and the boxes nest; move it outside and the nesting disappears.</p>`,
});

/* ---------- §83–84 vacuum vector and Tomita operator ---------- */
scene({
  id: "tomita", track: "aqft", title: "Vacuum vector and the Tomita operator", sections: [83, 84],
  summary: "Ω cyclic (𝓜Ω dense) and separating (AΩ = 0 ⇒ A = 0) for 𝓜 unlocks modular theory: S₀(AΩ) = A*Ω, and its polar decomposition S = JΔ<sup>1/2</sup> splits it into the modular conjugation J and the modular operator Δ. Computed on M_n acting on ℂⁿ ⊗ ℂⁿ.",
  refs: ["takesaki1970", "br1987", "haag"],
  init: () => ({ p1: 0.6, p2: 0.3, n3: true }),
  controls: (c) => `${slider("p1", "Schmidt weight p₁", 0, 1, 0.01, c.s.p1, (v) => v.toFixed(2))} ${slider("p2", "p₂", 0, 1, 0.01, c.s.p2, (v) => v.toFixed(2))} ${toggle("n3", "three levels", c.s.n3)}`,
  panels: {
    space: (c) => {
      const p = c.s.n3 ? [c.s.p1, c.s.p2, Math.max(0, 1 - c.s.p1 - c.s.p2)] : [c.s.p1, 1 - c.s.p1];
      const cs = AQ.cyclicSeparating(p);
      return { title: "Ω = ∑ √p_i e_i ⊗ e_i", sub: `Schmidt rank ${cs.schmidtRank} of ${cs.n}`, body: barChart({ W: 400, H: 160, items: p.map((x, i) => ({ label: `p${i + 1}`, value: Math.max(0, x), cls: x > 1e-12 ? "aqft" : "ck" })), showValues: true, vfmt: (v) => v.toFixed(2) }), foot: `dim 𝓜Ω = ${cs.dimMOmega} of ${cs.dimH}: cyclic ${cs.cyclic ? '<span class="pass">yes</span>' : '<span class="fail">no</span>'}, separating ${cs.separating ? '<span class="pass">yes</span>' : '<span class="fail">no</span>'}.` };
    },
    algebra: (c) => {
      const p = c.s.n3 ? [c.s.p1, c.s.p2, 1 - c.s.p1 - c.s.p2] : [c.s.p1, 1 - c.s.p1];
      if (p.some((x) => x <= 1e-9)) return { title: "NO MODULAR THEORY", body: `<p class="small">With a zero Schmidt weight Ω is neither cyclic nor separating, S is not densely defined in the needed way, and Tomita–Takesaki theory does not apply. Raise every weight above zero.</p>` };
      const T = AQ.tomita(LA.diag(p));
      return { title: "S = JΔ^{1/2}, CHECKED", sub: "matrix surrogate", body: kv([["‖S(AΩ) − A*Ω‖", T.check.tomita.toExponential(1)], ["‖JΔ^{1/2} − S‖ (on a probe)", T.check.polar.toExponential(1)], ["Δ X = ρXρ⁻¹", T.check.deltaClosedForm.toExponential(1)], ["J X = X*", T.check.jIsAdjoint.toExponential(1)], ["J² = 1", T.check.jSquared.toExponential(1)], ["JΩ = Ω", T.check.jOmega.toExponential(1)]]) };
    },
    diagram: () => ({ title: "THE SPLIT", body: `<pre class="small" style="font-family:var(--mono)">Tomita operator S\n      ↓ polar decomposition\nJ                  Δ\nmodular conjugation  modular operator</pre>${formula("S_0(A\\Omega) = A^*\\Omega,\\qquad S = J\\Delta^{1/2},\\qquad \\Delta = S^*S")}` }),
    field: (c) => {
      const p = c.s.n3 ? [c.s.p1, c.s.p2, 1 - c.s.p1 - c.s.p2] : [c.s.p1, 1 - c.s.p1];
      if (p.some((x) => x <= 1e-9)) return { title: "Δ", body: "<p class='small'>undefined</p>" };
      const T = AQ.tomita(LA.diag(p));
      return { title: "THE MODULAR OPERATOR Δ", sub: `${T.n * T.n} × ${T.n * T.n}, |entries|`, body: svg(220, 220, heatmap(LA.toArray(T.Delta), { x: 10, y: 10, size: 200 / (T.n * T.n), cls: "aqft", name: "Δ" }), "Delta") };
    },
  },
  notes: () => `<p>In the surrogate the Hilbert space is M_n with ⟨X, Y⟩ = Tr X*Y, 𝓜 acts by left multiplication and Ω = ρ^{1/2}. The engine builds S as an antilinear map, forms Δ = S*S, takes its square root by diagonalization, and gets J = SΔ^{−1/2}; it then checks the closed forms ΔX = ρXρ⁻¹ and JX = X* to rounding error.</p>`,
});

/* ---------- §85–86 modular flow and modular spectrum ---------- */
scene({
  id: "modflow", track: "aqft", title: "Modular flow and the modular Hamiltonian", sections: [85, 86],
  summary: "σ_t(A) = Δ<sup>it</sup>AΔ<sup>−it</sup>: an observable moves through algebra space as the modular time t changes. With K = −log Δ, Δ<sup>it</sup> = e<sup>−itK</sup> looks like quantum evolution — but it is MODULAR FLOW, defined by the algebra and the state, not ordinary spacetime evolution in general.",
  refs: ["takesaki1970", "br1987", "connes1973"],
  init: () => ({ p: 0.75, t: 0.6 }),
  anim: ["field"],
  controls: (c) => `${slider("p", "state ρ = diag(p, 1 − p)", 0.51, 0.99, 0.01, c.s.p, (v) => v.toFixed(2))} ${slider("t", "modular time t", 0, 6.28, 0.01, c.s.t, (v) => v.toFixed(2))}`,
  panels: {
    field: (c) => {
      const rho = AQ.qubitState(c.s.p);
      const ts = Q.linspace(0, Math.max(0.01, c.s.t), 60);
      const traj = ts.map((t) => AQ.blochVector(AQ.modularFlow(rho, AQ.PAULI.X, t)));
      const tt = c.s.t + 0.15 * Math.sin(c.t);
      return { title: "MODULAR FLOW", sub: "σ_t(X) on the Bloch sphere", body: svg(400, 210, bloch(200, 105, 80, traj, { head: AQ.blochVector(AQ.modularFlow(rho, AQ.PAULI.X, tt)) }), "modular orbit"), foot: `angular speed log(p/(1−p)) = ${fmt(Math.log(c.s.p / (1 - c.s.p)), 4)} per unit modular time.` };
    },
    algebra: (c) => {
      const T = AQ.tomita(AQ.qubitState(c.s.p));
      return { title: "MODULAR SPECTRUM", sub: "eigenvalues of Δ and K = −log Δ", body: barChart({ W: 400, H: 170, items: T.deltaEigenvalues.map((d, i) => ({ label: `Δ: ${fmt(d, 3)}`, value: -Math.log(d), cls: "aqft", tip: `Δ eigenvalue ${fmt(d, 5)}, K = ${fmt(-Math.log(d), 5)}` })), ylabel: "K = −log Δ" }), foot: "Spec Δ = {p_i/p_j}: here {p/(1−p), 1, 1, (1−p)/p}." };
    },
    diagram: (c) => {
      const kms = AQ.kmsCheck(AQ.qubitState(c.s.p), AQ.PAULI.X, AQ.PAULI.Y);
      return { title: "Δ^{it} = e^{−itK}", body: formula("\\sigma_t(A) = \\Delta^{it}A\\Delta^{-it},\\qquad \\Delta^{it} = e^{-itK}") + kv([["KMS: ω(A σ_{−i}(B)) − ω(BA)", kms.diff.toExponential(1)], ["ρ = e^{−H}/Z gives σ_t = time evolution at −t", "for the thermal reading"]]) };
    },
    space: () => ({ title: "NOT SPACETIME EVOLUTION", body: `<p class="small">The flow is fixed by (𝓜, Ω) alone. For a thermal state it is time evolution (rescaled); for the vacuum and a wedge it is a boost (next view); for a general region it has no geometric meaning.</p>${sceneLink("wedge", "the wedge")}` }),
  },
  notes: () => `<p>This is the first place on the page where a time-like dynamics comes out of algebra and state data rather than an externally supplied Hamiltonian. The finite surrogate makes every step a matrix computation: σ_t(A) = ρ^{it}Aρ^{−it}.</p>`,
});

/* ---------- §87 wedge region ---------- */
scene({
  id: "wedge", track: "aqft", title: "Wedge region and boosts", sections: [87],
  summary: "A Rindler wedge W = {x > |t|} in Minkowski spacetime and the Lorentz boosts that preserve it. Advanced annotation: in suitable relativistic QFT settings the modular flow of the vacuum for the wedge algebra is the boost, Δ<sup>it</sup> = U(Λ(−2πt)) (Bisognano–Wichmann).",
  refs: ["bw1975", "haag", "witten2018"],
  init: () => ({ t: 0.05 }),
  anim: ["space"],
  controls: (c) => slider("t", "modular time t", -0.3, 0.3, 0.005, c.s.t, (v) => v.toFixed(3)),
  panels: {
    space: (c) => {
      const M = minkowski({ W: 400, H: 250, scale: 50, cone: false });
      let s = M.s + poly([M.P(0, 0), M.P(4, 4), M.P(-4, 4)], "bgaqft", 'stroke="var(--aqft)"') + txt(...M.P(0.2, 3.1), "W", "lbl");
      for (const a of [0.5, 1, 1.6, 2.3]) s += path(pathD(Q.linspace(-1.6, 1.6, 40).map((eta) => M.P(a * Math.sinh(eta), a * Math.cosh(eta)))), "aqft", 'fill="none" opacity="0.6"');
      const anim = c.s.t + 0.05 * Math.sin(c.t * 0.8);
      for (const p of [[0.2, 1], [-0.4, 1.6], [0.6, 2.2]]) { const q = AQ.modularBoost(anim, p); s += circ(...M.P(...p), 3, "vtx") + arrow(...M.P(...p), ...M.P(...q), "ck") + circ(...M.P(...q), 4, "fck"); }
      return { title: "RINDLER WEDGE", sub: "boost orbits are hyperbolae", body: svg(400, 250, s, "wedge") };
    },
    algebra: (c) => ({ title: "BISOGNANO–WICHMANN (ADVANCED)", body: formula("\\Delta_W^{it} = U(\\Lambda_W(-2\\pi t))") + kv([["modular time t", c.s.t.toFixed(3)], ["boost rapidity", fmt(-2 * PI * c.s.t, 4)], ["(0.2, 1) ↦", AQ.modularBoost(c.s.t, [0.2, 1]).map((x) => fmt(x, 4)).join(", ")], ["x² − t² before → after", (() => { const q = AQ.modularBoost(c.s.t, [0.2, 1]); return `${fmt(1 - 0.04, 6)} → ${fmt(q[1] ** 2 - q[0] ** 2, 6)}`; })()]]) + `<p class="small">In suitable relativistic QFT settings (Wightman fields, the vacuum, the wedge algebra), modular flow is geometric. For other regions it generally is not.</p>` }),
  },
  notes: () => `<p>This is the cleanest bridge from abstract modular theory back to spacetime: the algebra and the vacuum alone produce the boost that preserves the wedge, and the modular conjugation J is the reflection (t, x) ↦ (−t, −x) combined with charge conjugation.</p>`,
});

/* ---------- §122, §133 flagship: region to modular flow ---------- */
const AQ_STEPS = ["select region 𝒪", "local algebra 𝒜(𝒪)", "select vacuum Ω", "cyclic and separating", "construct S", "S = JΔ^{1/2}", "evolve with Δ^{it}", "inspect the orbit"];
scene({
  id: "flagship-aqft", track: "aqft", title: "From region to modular flow", sections: [122, 133],
  summary: "The third flagship: Minkowski spacetime → select a region 𝒪 → 𝒜(𝒪) → choose the vacuum Ω → cyclic and separating → S(AΩ) = A*Ω → S = JΔ<sup>1/2</sup> → Δ<sup>it</sup> → modular flow. Time-like dynamics emerging from algebra and state, computed on a matrix surrogate, with the wedge's boosts as the geometric comparison.",
  refs: ["takesaki1970", "bw1975", "haag", "yngvason2005"],
  init: () => ({ step: 0, p: 0.75, t: 0.6 }),
  anim: ["field"],
  controls: (c) => `${stepper("step", AQ_STEPS, c.s.step)} ${slider("p", "vacuum weights (p, 1 − p)", 0.51, 0.99, 0.01, c.s.p, (v) => v.toFixed(2))} ${slider("t", "modular time t", 0, 6.28, 0.01, c.s.t, (v) => v.toFixed(2))}`,
  present: ["space", "field"],
  panels: {
    space: (c) => {
      const M = minkowski({ W: 400, H: 220, scale: 45, cone: false });
      let s = M.s + poly([M.P(1.2, 0), M.P(0, 1.2), M.P(-1.2, 0), M.P(0, -1.2)], c.s.step >= 0 ? "bgaqft" : "", 'stroke="var(--aqft)" stroke-width="1.6"') + txt(...M.P(1.35, 0), "𝒪", "lbl", 'text-anchor="middle"');
      if (c.s.step >= 1) s += txt(...M.P(-1.6, 2.2), "𝒜(𝒪) ≈ M₂ ⊗ 1 (surrogate)", "xs ink2");
      if (c.s.step >= 7) for (const a of [0.6, 1.2]) s += path(pathD(Q.linspace(-1.2, 1.2, 30).map((eta) => M.P(a * Math.sinh(eta), a * Math.cosh(eta)))), "ck", 'fill="none" opacity="0.6"');
      return { title: "MINKOWSKI SPACETIME", sub: c.s.step >= 7 ? "with wedge boost orbits for comparison" : "a region 𝒪", body: svg(400, 220, s, "region") };
    },
    field: (c) => {
      const rho = AQ.qubitState(c.s.p);
      if (c.s.step < 6) return { title: "STATE AND ALGEBRA", sub: "", body: svg(400, 200, bloch(200, 100, 80, [], { head: [0, 0, 2 * c.s.p - 1], cls: "aqft" }) + txt(14, 194, `reduced state ρ = diag(${c.s.p.toFixed(2)}, ${(1 - c.s.p).toFixed(2)}) of the vacuum on 𝒜(𝒪)`, "xs ink2"), "state") };
      const ts = Q.linspace(0, Math.max(0.01, c.s.t), 60);
      const traj = ts.map((t) => AQ.blochVector(AQ.modularFlow(rho, AQ.PAULI.X, t)));
      return { title: "MODULAR ORBIT", sub: "σ_t(σ_x)", body: svg(400, 210, bloch(200, 105, 80, traj, { head: AQ.blochVector(AQ.modularFlow(rho, AQ.PAULI.X, c.s.t + 0.1 * Math.sin(c.t))) }), "orbit") };
    },
    algebra: (c) => {
      const r = ENG.regionToModular({ p: [c.s.p, 1 - c.s.p], t: c.s.t });
      const rows = [
        ["region 𝒪 (double cone)", "—"],
        ["𝒜(𝒪), type III₁ in QFT", "M₂(ℂ) ⊗ 1 surrogate (type I)"],
        ["vacuum Ω", `Ω = √p e₁⊗e₁ + √(1−p) e₂⊗e₂, p = ${c.s.p.toFixed(2)}`],
        ["Reeh–Schlieder: Ω cyclic and separating", `Schmidt rank ${r.cyclic.schmidtRank}: cyclic ${r.cyclic.cyclic ? "✓" : "✗"}, separating ${r.cyclic.separating ? "✓" : "✗"}`],
        ["S(AΩ) = A*Ω", `‖S(AΩ) − A*Ω‖ = ${r.check.tomita.toExponential(1)}`],
        ["S = JΔ^{1/2}", `polar check ${r.check.polar.toExponential(1)}; Spec Δ = ${r.deltaEigenvalues.map((x) => fmt(x, 3)).join(", ")}`],
        ["Δ^{it}", `σ_t at t = ${c.s.t.toFixed(2)}; KMS ${r.kms.toExponential(1)}`],
        ["modular orbit", `wedge comparison: rapidity −2πt = ${fmt(r.wedge.rapidity, 3)}`],
      ];
      return { title: "SPACETIME / QFT | SURROGATE", sub: `step ${c.s.step + 1} of ${AQ_STEPS.length}`, body: table(["spacetime / QFT", "computed surrogate"], rows.map((row, i) => (i === c.s.step ? row.map((x) => `<b>${esc(x)}</b>`) : i < c.s.step ? row.map(esc) : row.map((x) => `<span class="muted">${esc(x)}</span>`)))) };
    },
    diagram: (c) => ({ title: "THE PIPELINE", body: `<ol class="small">${AQ_STEPS.map((t, i) => `<li${i === c.s.step ? ' style="font-weight:650"' : i > c.s.step ? ' class="muted"' : ""}>${supify(esc(t))}</li>`).join("")}</ol>` }),
  },
  notes: () => `<p>MINKOWSKI SPACETIME ↓ select region 𝒪 ↓ 𝒜(𝒪) ↓ choose vacuum Ω ↓ cyclic + separating ↓ S(AΩ) = A*Ω ↓ S = JΔ<sup>1/2</sup> ↓ Δ<sup>it</sup> ↓ modular flow. The left column states what holds in relativistic QFT (the Reeh–Schlieder theorem makes the vacuum cyclic and separating for every local algebra; the algebras are type III₁ under standard hypotheses); the right column computes the same construction on a finite surrogate.</p>`,
  md: (c) => ({ title: "From region to modular flow", sections: REP.modularMarkdown(ENG.regionToModular({ p: [c.s.p, 1 - c.s.p], t: c.s.t })) }),
  deckKind: "modular",
});
