/* Connes–Kreimer track: the Hopf algebra of Feynman graphs, forests, the antipode, characters,
   Birkhoff decomposition, the Riemann sphere and the renormalization group (spec §43–§59, §98–§100,
   §112). Numbers on nested graphs come from the toy Feynman rules φ(T) = e^{−|T|εL}/(T! ε^{|T|}),
   always labelled; the one-loop vacuum polarization uses real QED values. */

const CK_GRAPHS = ["sigma2_rainbow", "sigma2_crossed", "sigma2_vp", "pi2_se", "pi2_crossed", "lambda2_ladder", "sigma3_rainbow", "sigma3_double"];
const TOY_NOTE = "Toy Feynman rules (the Connes–Kreimer iterated-integral model): the combinatorics is the graph's, the Laurent coefficients are the model's, not QED's.";
const graphSelect = (key, value, ids = CK_GRAPHS) => `<label class="ctl">graph <select data-bind="s.${key}">${ids.map((id) => `<option value="${id}"${id === value ? " selected" : ""}>${esc(GR.byId(id).name)}</option>`).join("")}</select></label>`;
/* The chosen catalogue graph and its divergent proper 1PI subgraphs. */
const graphWithSubs = (c) => { const g = GR.byId(c.s.graph); return { g, subs: GR.divergentSubgraphs(g) }; };
/* Boxes for every divergent subgraph, nested ones drawn larger. */
function subgraphBoxes(g, subs, opts = {}) {
  return subs.map((s, i) => {
    const depth = subs.filter((t) => t !== s && GR.relation(s, t) === "contains").length;
    return { vertices: s.vertices, edges: s.edges, depth, cls: opts.sel === i ? "sel" : "", label: opts.labels ? `γ${i + 1}` : "", link: `sub${i}`, act: opts.act, arg: i };
  });
}
const monoNames = (m) => (m === "" ? "1" : HO.factors(m).map((k) => HO.graphOf(k).name).join(" · "));

/* ---------- §43 entering Connes–Kreimer ---------- */
scene({
  id: "ck-enter", track: "ck", title: "Feynman graphs as algebra generators", sections: [43],
  summary: "Turn a collection of 1PI Feynman graphs into generators of a commutative algebra 𝓗. Multiplication is disjoint union; the empty graph is the unit. This algebra organizes the combinatorics of subdivergences.",
  refs: ["ck1998", "ck2000", "kreimer1998"],
  graphs: true,
  panels: {
    diagram: () => {
      const ids = ["sigma1", "pi1", "lambda1"];
      let s = "";
      ids.forEach((id, i) => { const x = 10 + i * 130; s += `<rect x="${x}" y="4" width="122" height="84" rx="6" fill="var(--panel)" stroke="var(--rule)"/>` + feynman(GR.byId(id), [x + 4, 6, 114, 70]) + txt(x + 61, 98, `Γ${["₁", "₂", "₃"][i]}`, "lbl serif", 'text-anchor="middle"') + arrow(x + 61, 104, x + 61, 126, "ck"); });
      s += txt(200, 146, "generators of 𝓗", "lbl", 'text-anchor="middle"');
      return { title: "GRAPHS → GENERATORS", sub: "1PI, divergent residue", body: svg(400, 156, s, "generators") };
    },
    field: () => {
      const g1 = GR.byId("sigma1"), g2 = GR.byId("pi1");
      const s = feynman(g1, [10, 10, 170, 100]) + txt(195, 64, "·", "lbl", 'style="font-size:22px"') + feynman(g2, [215, 10, 170, 100]) + txt(200, 140, "Γ₁Γ₂ = disjoint union of Γ₁ and Γ₂", "sm", 'text-anchor="middle"') + txt(200, 160, "1 = the empty graph;  ε(Γ) = 0 for every nonempty Γ", "xs ink2", 'text-anchor="middle"');
      return { title: "MULTIPLICATION", sub: "disjoint union", body: svg(400, 170, s, "product") };
    },
    algebra: () => {
      const ks = ["sigma1", "pi1", "lambda1", "sigma2_rainbow"].map((id) => HO.keyOf(GR.byId(id)));
      return { title: "AN ELEMENT OF 𝓗", sub: "polynomials in graphs", body: `<p class="formula">${tex("X = 2\\,\\Gamma_1\\Gamma_2 - \\Gamma_3 + \\Gamma_4")}</p><p class="small">Graphs are identified up to isomorphism by a canonical form computed from the graph (vertex permutations respecting types and charge flow). Four canonical keys: ${ks.map((k) => `<code class="tiny">${esc(k.slice(0, 26))}…</code>`).join(", ")}.</p>` };
    },
    space: () => ({ title: "WHY AN ALGEBRA", body: `<p class="small">Renormalization of a graph needs its subgraphs and the graphs left after contracting them. Encoding "split into parts" as a coproduct makes the Bogoliubov–Zimmermann recursion an algebraic identity: the antipode.</p>${sceneLink("coproduct", "the coproduct")}` }),
  },
  notes: () => `<p>Connes and Kreimer showed that the combinatorics of subdivergences is the structure of a commutative Hopf algebra 𝓗 freely generated by 1PI graphs with divergent residues; regularized Feynman rules are characters of 𝓗 and renormalization is the Birkhoff decomposition of the resulting loop of characters.</p>`,
});

/* ---------- §44, §98–100 diagram builder and 1PI detector ---------- */
const BUILDER_TOOLS = [["move", "move"], ["vertex", "+ QED vertex"], ["e", "+ internal electron"], ["g", "+ internal photon"], ["xe", "+ external electron"], ["xp", "+ external positron"], ["xg", "+ external photon"], ["del", "delete"], ["cut", "cut an internal line"]];
function builderGraph(s) {
  if (!s.custom) { const g = GR.byId(s.graph); s.custom = JSON.parse(JSON.stringify({ id: "built", name: `built from ${g.name}`, vertices: g.vertices, edges: g.edges })); }
  return s.custom;
}
let BUILD_ID = 0;
scene({
  id: "builder", track: "ck", title: "Diagram builder and 1PI detector", sections: [44, 98, 99, 100],
  summary: "Assemble a QED graph from primitives — external electron, positron and photon, internal electron and photon, QED vertex — and read charge flow, valence, loop number L = I − V + 1, connectedness, 1PI status, the superficial degree of divergence and the divergent subgraphs, live. Cut any internal line: if the graph stays connected for every single cut, it is 1PI.",
  refs: ["ps", "ck2000"],
  graphs: true,
  init: () => ({ graph: "pi2_crossed", tool: "cut", pending: null, cuts: [], custom: null }),
  controls: (c) => `${graphSelect("graph", c.s.graph, ["tree_emu", "sigma1", "pi1", "lambda1", "pi1_chain", "lbl", ...CK_GRAPHS])} ${actBtn("bclear", "blank canvas")} ${actBtn("breset", "reload graph")}<br>${seg("tool", BUILDER_TOOLS, c.s.tool, "Tool")}`,
  onSet: (c, key) => { if (key === "graph") { c.s.custom = null; c.s.cuts = []; c.s.pending = null; } if (key === "tool") c.s.pending = null; },
  actions: {
    bclear: (c) => { c.s.custom = { id: "built", name: "built graph", vertices: [], edges: [] }; c.s.cuts = []; c.s.tool = "vertex"; },
    breset: (c) => { c.s.custom = null; c.s.cuts = []; },
    edge: (c, id) => {
      const g = builderGraph(c.s);
      const e = g.edges.find((x) => x.id === id);
      if (!e) return;
      if (c.s.tool === "del") { g.edges = g.edges.filter((x) => x.id !== id); g.vertices = g.vertices.filter((v) => v.kind !== "ext" || g.edges.some((x) => x.a === v.id || x.b === v.id)); }
      else if (c.s.tool === "cut") { const internal = !GR.isExt(g, e.a) && !GR.isExt(g, e.b); if (internal) c.s.cuts = c.s.cuts.includes(id) ? c.s.cuts.filter((x) => x !== id) : [id]; }
    },
  },
  drag: {
    canvas: (c, p, phase) => {
      if (phase !== "start") return;
      const g = builderGraph(c.s);
      if (c.s.tool === "vertex") g.vertices.push({ id: `n${++BUILD_ID}`, x: clamp(p.x / 2, 5, 195), y: clamp(p.y / 2, 5, 115), kind: "v" });
      c.s.pending = null;
    },
    vtx: (c, p, phase, id) => {
      const g = builderGraph(c.s);
      const v = g.vertices.find((x) => x.id === id);
      if (!v) return;
      const t = c.s.tool;
      if (t === "move") { v.x = clamp(p.x / 2, 3, 197); v.y = clamp(p.y / 2, 3, 117); return; }
      if (phase !== "start") return;
      if (t === "del") { g.vertices = g.vertices.filter((x) => x.id !== id); g.edges = g.edges.filter((e) => e.a !== id && e.b !== id); g.vertices = g.vertices.filter((u) => u.kind !== "ext" || g.edges.some((e) => e.a === u.id || e.b === u.id)); return; }
      if (t === "e" || t === "g") {
        if (!c.s.pending) { c.s.pending = id; return; }
        if (c.s.pending !== id || t === "e") {
          const same = g.edges.filter((e) => (e.a === c.s.pending && e.b === id) || (e.a === id && e.b === c.s.pending)).length;
          g.edges.push({ id: `l${++BUILD_ID}`, a: c.s.pending, b: id, type: t, bend: same ? (same % 2 ? 30 : -30) : 0 });
        }
        c.s.pending = null;
        return;
      }
      if (t === "xe" || t === "xp" || t === "xg") {
        const dir = v.x < 100 ? -1 : 1, nid = `x${++BUILD_ID}`;
        const ext = { id: nid, x: clamp(v.x + dir * 26, 2, 198), y: clamp(v.y + (g.vertices.filter((u) => u.kind === "ext").length % 2 ? 14 : -14), 2, 118), kind: "ext" };
        g.vertices.push(ext);
        // electron: arrow into the graph from the left, out to the right; positron: the reverse arrow
        const intoGraph = (t === "xe") === (dir < 0);
        g.edges.push(t === "xg" ? { id: `l${++BUILD_ID}`, a: nid, b: id, type: "g", bend: 0 } : intoGraph ? { id: `l${++BUILD_ID}`, a: nid, b: id, type: "e", bend: 0 } : { id: `l${++BUILD_ID}`, a: id, b: nid, type: "e", bend: 0 });
      }
    },
  },
  panels: {
    diagram: (c) => {
      const g = builderGraph(c.s);
      GR.analyse(g);
      const cut = new Set(c.s.cuts);
      const glow = c.s.tool === "cut" && !cut.size ? [] : [];
      let s = rect(0, 0, 400, 240, "", 'fill="transparent" data-drag="canvas"');
      s += feynman(g, [0, 0, 400, 240], { fit: false, act: "edge", faded: cut, glow, tip: (e) => `${e.type === "g" ? "photon" : "fermion"} line${GR.isExt(g, e.a) || GR.isExt(g, e.b) ? " (external)" : " (internal)"} — ${c.s.tool === "cut" ? "click to cut" : c.s.tool === "del" ? "click to delete" : ""}` });
      for (const v of g.vertices) s += circ(v.x * 2, v.y * 2, 9, "hit", `data-drag="vtx" data-arg="${v.id}" data-tip="${v.kind === "ext" ? "external end" : "vertex"} ${v.id}"`) + (c.s.pending === v.id ? circ(v.x * 2, v.y * 2, 8, "", 'fill="none" stroke="var(--ck)" stroke-width="2"') : "");
      if (cut.size) { const after = GR.components(g, { skipEdge: [...cut][0] }).count; s += txt(10, 232, after > 1 ? "cut disconnects the graph: this line is a bridge → not 1PI" : "still connected after this cut", "sm", `style="fill:${after > 1 ? "var(--bad)" : "var(--ok)"}"`); }
      return { title: "CANVAS", sub: `tool: ${BUILDER_TOOLS.find((t) => t[0] === c.s.tool)[1]}`, body: svg(400, 240, s, "graph builder"), foot: c.s.tool === "vertex" ? "Click empty space to add a vertex." : c.s.tool === "e" || c.s.tool === "g" ? "Click two vertices to join them (electron lines run from the first to the second)." : c.s.tool.startsWith("x") ? "Click a vertex to attach an external leg." : c.s.tool === "cut" ? "Click an internal line to cut it." : "Drag vertices to rearrange." };
    },
    algebra: (c) => {
      const g = builderGraph(c.s);
      const a = ENG.analyseGraph(g);
      const ok = (b) => (b ? '<span class="pass">✓</span>' : '<span class="fail">✗</span>');
      return { title: "CHECKS", sub: "recomputed on every edit", body: kv([
        ["charge flow & valence", `${ok(a.valid)} ${a.issues.length ? esc(a.issues[0].message) : "every vertex: one fermion in, one out, one photon"}`],
        ["loop number", `${esc(a.loopFormula)}`],
        ["connected", ok(a.connected)],
        ["1PI", `${ok(a.onePI)} ${a.bridges.length ? `bridge${a.bridges.length > 1 ? "s" : ""}: ${a.bridges.join(", ")}` : ""}`],
        ["external legs", `${a.external.Ee} fermion, ${a.external.Eg} photon → ${esc(a.residue.name)}`],
        ["superficial degree", `ω = 4 − (3/2)E_e − E_γ = ${fmt(a.omega, 3)}: ${esc(a.verdict)}`],
        ["divergent subgraphs", a.divergentSubgraphs.length ? a.divergentSubgraphs.map((s2) => `${esc(s2.residue.name)} {${s2.edges.join(",")}}`).join("; ") : "none"],
      ]) + (a.residue.note ? `<p class="small muted">${esc(a.residue.note)}</p>` : "") + (a.coproduct ? `<p class="small">Coproduct: ${a.coproduct.length} terms, ${a.forestCount} forests. ${sceneLink("coproduct", "see it")}</p>` : "") };
    },
    field: (c) => {
      const g = builderGraph(c.s), a = GR.analyse(g);
      if (!a.cycles.length) return { title: "INDEPENDENT LOOPS", body: "<p class='small'>No loops: a tree graph has no free momentum.</p>" };
      let s = "";
      a.cycles.slice(0, 3).forEach((cy, i) => { const x = i * 133; s += `<g>${feynman(g, [x + 2, 4, 128, 90], { glow: cy.edges, arrows: false })}</g>` + txt(x + 66, 110, `loop k${i + 1}`, "xs ink2", 'text-anchor="middle"'); });
      return { title: "INDEPENDENT MOMENTUM LOOPS", sub: `${a.cycles.length} = L`, body: svg(400, 118, s, "cycle basis") };
    },
    space: (c) => {
      const a = GR.analyse(builderGraph(c.s));
      return { title: "POWER COUNTING", sub: "superficial degree", body: barChart({ W: 400, H: 170, items: [{ label: "loop ∫d⁴k", value: a.omegaParts.loopPower, cls: "ck" }, { label: "propagators", value: a.omegaParts.propagatorPower, cls: "qft" }, { label: "numerators", value: a.omegaParts.numeratorPower, cls: "aqft" }, { label: "ω", value: a.omegaParts.fromPowerCounting, cls: a.omega >= 0 ? "ck" : "ncg" }], showValues: true, vfmt: (v) => String(v) }), foot: "loop integration adds momentum powers; propagators remove them; (counterterm) numerators may add powers. Caveats: symmetry can lower ω, and subdivergences are not seen by ω." };
    },
  },
  notes: () => `<p>Each check is computed from the edge list: valence by counting line ends at each vertex, the loop number from ${tex("L = I - V + C")}, connectedness by union–find, 1PI status by removing each internal line in turn, ω from the external legs (and, as a cross-check, by power counting), and the divergent subgraphs by enumerating every subset of internal lines.</p>`,
});

/* ---------- §45, §47 divergent subgraphs and the nested divergence tree ---------- */
scene({
  id: "subgraphs", track: "ck", title: "Divergent subgraphs and why naive subtraction fails", sections: [45, 47],
  summary: "Every superficially divergent proper 1PI subgraph, boxed (nested boxes for nested subgraphs), and the containment tree they form. Then the failure of naive subtraction: removing only the overall pole of a nested graph leaves a counterterm that depends on μ.",
  refs: ["zimmermann1969", "ck2000", "manchon2008", "kreimer1999"],
  graphs: true,
  init: () => ({ graph: "sigma3_rainbow", sel: -1, L: 0.6 }),
  controls: (c) => `${graphSelect("graph", c.s.graph)} ${slider("L", "log μ (toy)", -1, 2, 0.01, c.s.L, (v) => v.toFixed(2))}`,
  actions: { pick: (c, arg) => { c.s.sel = c.s.sel === Number(arg) ? -1 : Number(arg); } },
  panels: {
    diagram: (c) => {
      const { g, subs } = graphWithSubs(c);
      return { title: "DIVERGENT SUBGRAPHS", sub: `${subs.length} found`, body: svg(400, 240, feynman(g, [16, 16, 368, 210], { boxes: subgraphBoxes(g, subs, { labels: true, sel: c.s.sel, act: "pick" }) }), "subgraphs"), foot: subs.map((s, i) => `<span data-link="sub${i}">γ${i + 1}: ${esc(s.residue.name)} (L = ${s.L}, ω = ${s.omega})</span>`).join(" · ") || "no subdivergences" };
    },
    field: (c) => {
      const { g, subs } = graphWithSubs(c), tree = GR.containmentTree(g, subs);
      const root = tree.findIndex((n) => n.whole);
      const lines = [];
      const walk = (idx, prefix, last) => { const n = tree[idx]; lines.push(`${prefix}${idx === root ? "" : last ? "└── " : "├── "}${n.whole ? "Γ" : `γ${idx + 1}`}`); const ch = tree.filter((m) => m.parent === idx); ch.forEach((m, k) => walk(m.index, idx === root ? "" : prefix + (last ? "    " : "│   "), k === ch.length - 1)); };
      walk(root, "", true);
      const ovl = GR.analyse(g).overlapping;
      return { title: "CONTAINMENT TREE", sub: ovl ? "overlapping: not a tree" : "nesting", body: `<pre class="small" style="font-family:var(--mono)">${esc(lines.join("\n"))}</pre>${ovl ? '<p class="small">Two subgraphs share lines without either containing the other: overlapping divergences. Each maximal forest gives its own tree.</p>' : ""}<p class="small">Forest data: ${HO.forests(g).forests.length} forests (sets of non-overlapping subgraphs, ∅ included).</p>` };
    },
    algebra: (c) => {
      const g = GR.byId(c.s.graph), phi = HO.toyCharacter(c.s.L, 6), key = HO.keyOf(g);
      const naive = LS.clean(LS.neg(LS.pole(phi.onKey(key))));
      const phi2 = HO.toyCharacter(c.s.L + 0.5, 6), naive2 = LS.clean(LS.neg(LS.pole(phi2.onKey(key))));
      const B = HO.birkhoff(phi), B2 = HO.birkhoff(phi2);
      return { title: "NAIVE VS RECURSIVE SUBTRACTION", sub: "toy Feynman rules", body: table(["", `at log μ = ${c.s.L.toFixed(2)}`, `at log μ = ${(c.s.L + 0.5).toFixed(2)}`], [["naive: −T φ(Γ)", esc(LS.toText(naive, { sig: 4 })), esc(LS.toText(naive2, { sig: 4 }))], ["recursive: γ₋(Γ)", esc(LS.toText(B.minus.onKey(key), { sig: 4 })), esc(LS.toText(B2.minus.onKey(key), { sig: 4 }))]]) + `<p class="small">The naive counterterm changes with μ: it multiplies a log μ by a pole, a non-local term no Lagrangian counterterm can supply. Subtracting the subdivergences first (the forest formula, the antipode) gives μ-independent counterterms.</p><p class="tiny muted">${TOY_NOTE}</p>` };
    },
    space: () => ({ title: "SUPERFICIAL DIVERGENCE", body: `<p class="small">QED's divergent residues: electron self-energy (ω = 1), vacuum polarization (ω = 2), vertex (ω = 0). Light-by-light (ω = 0) is finite by gauge invariance; odd numbers of photons vanish by Furry's theorem.</p>` }),
  },
  notes: () => `<p>A subgraph is proper if it is not the whole graph, 1PI if it survives every single cut, and superficially divergent if ω ≥ 0 for its external legs. Nested subgraphs (one inside another) can be renormalized from the inside out; overlapping ones cannot be ordered, which is where the algebraic treatment pays off.</p>`,
});

/* ---------- §46 the coproduct, animated ---------- */
function collapseGraph(g, sub, t) {
  const vs = new Set(sub.vertices);
  const pts = g.vertices.filter((v) => vs.has(v.id));
  const cx = Q.sum(pts.map((p) => p.x)) / pts.length, cy = Q.sum(pts.map((p) => p.y)) / pts.length;
  return { ...g, vertices: g.vertices.map((v) => (vs.has(v.id) ? { ...v, x: v.x + (cx - v.x) * t, y: v.y + (cy - v.y) * t } : v)), edges: g.edges.map((e) => ({ ...e, bend: sub.edges.includes(e.id) ? (e.bend || 0) * (1 - t) : e.bend })) };
}
scene({
  id: "coproduct", track: "ck", title: "Hopf coproduct", sections: [46],
  summary: "ΔΓ = Γ⊗1 + 1⊗Γ + ∑ γ⊗Γ/γ. Highlight a divergent subgraph γ, then physically collapse it to a vertex: the pair (γ, Γ/γ) is one branch. The sum over admissible subgraphs appears as the list of branches.",
  refs: ["ck2000", "kreimer1998"],
  graphs: true,
  init: () => ({ graph: "sigma3_rainbow", term: 0, auto: true }),
  anim: ["diagram"],
  controls: (c) => `${graphSelect("graph", c.s.graph)} ${toggle("auto", "animate the collapse", c.s.auto)}`,
  onSet: (c, key) => { if (key === "graph") c.s.term = 0; },
  actions: { term: (c, arg) => { c.s.term = Number(arg); } },
  panels: {
    diagram: (c) => {
      const g = GR.byId(c.s.graph), terms = HO.coproductTerms(g);
      if (!terms.length) return { title: "Γ IS PRIMITIVE", body: svg(400, 200, feynman(g, [20, 10, 360, 180]), g.name) };
      const t = terms[Math.min(c.s.term, terms.length - 1)];
      const phase = c.s.auto ? (Math.sin(c.t * 0.9) + 1) / 2 : 1;
      let gg = g;
      for (const p of t.parts) gg = collapseGraph(gg, p, phase);
      const boxes = t.parts.map((p, i) => ({ vertices: p.vertices, edges: p.edges, cls: "sel", label: phase < 0.5 ? `γ${t.parts.length > 1 ? i + 1 : ""}` : "", depth: 0 }));
      return { title: "COLLAPSING γ", sub: `branch ${Math.min(c.s.term, terms.length - 1) + 1} of ${terms.length}`, body: svg(400, 230, feynman(gg, [16, 14, 368, 205], { boxes: phase < 0.85 ? boxes : [], faded: new Set(phase > 0.6 ? t.parts.flatMap((p) => p.edges) : []) }), "collapse"), foot: "Γ — select γ — contract it to a vertex: Γ/γ." };
    },
    field: (c) => {
      const g = GR.byId(c.s.graph), terms = HO.coproductTerms(g);
      const cellW = 400, rowH = 74;
      let s = txt(10, 16, "ΔΓ =", "lbl serif") + txt(48, 16, "Γ ⊗ 1  +  1 ⊗ Γ", "sm");
      terms.forEach((t, i) => {
        const y = 26 + i * rowH, on = i === Math.min(c.s.term, terms.length - 1);
        s += `<g data-act="term" data-arg="${i}" style="cursor:pointer"><rect x="4" y="${y}" width="${cellW - 8}" height="${rowH - 6}" rx="6" fill="${on ? "var(--ck-bg)" : "var(--panel)"}" stroke="var(--rule)"/>` + txt(14, y + 38, "+", "lbl");
        const lw = t.left.length > 1 ? 70 : 120;
        t.left.forEach((lg, k) => { s += feynman(lg, [26 + k * (lw + 6), y + 4, lw, rowH - 16], { hideExt: false }); });
        const lx = 26 + t.left.length * (lw + 6);
        s += txt(lx + 6, y + 38, "⊗", "lbl") + feynman(t.right, [lx + 24, y + 4, cellW - lx - 36, rowH - 16]) + "</g>";
      });
      return { title: "ALL BRANCHES", sub: `${terms.length + 2} terms`, body: svg(cellW, 30 + terms.length * rowH, s, "coproduct terms"), foot: "Click a branch to animate it. Products of disjoint subgraphs appear as several left factors." };
    },
    algebra: (c) => {
      const g = GR.byId(c.s.graph);
      const rows = HO.coproduct(g).map((t) => [esc(t.kind), esc(monoNames(t.left)), esc(monoNames(t.right))]);
      return { title: "THE COPRODUCT, SYMBOLICALLY", sub: "computed", body: table(["term", "left (subgraphs)", "right (quotient)"], rows) };
    },
    space: (c) => {
      const g = GR.byId(c.s.graph);
      const terms = HO.coproductTerms(g);
      return { title: "LOOP BOOKKEEPING", body: table(["γ", "L(γ)", "L(Γ/γ)", "sum"], terms.map((t) => { const Lg = t.parts.reduce((s2, p) => s2 + p.L, 0), Lq = GR.loopNumber(t.right); return [esc(t.parts.map((p) => p.residue.name).join(" · ")), Lg, Lq, Lg + Lq]; }), [1, 2, 3]) + `<p class="small">Contraction removes exactly the loops of γ: L(Γ/γ) = L(Γ) − L(γ) = ${GR.loopNumber(g)} − L(γ).</p>` };
    },
  },
  notes: () => `<p>${formula("\\Delta\\Gamma = \\Gamma\\otimes 1 + 1\\otimes\\Gamma + \\sum_{\\gamma\\subsetneq\\Gamma}\\gamma\\otimes\\Gamma/\\gamma")} The sum runs over nonempty products of disjoint, divergent, proper 1PI subgraphs. Contracting a self-energy or vacuum-polarization subgraph leaves a two-point vertex (drawn ⊗); contracting a vertex subgraph leaves a QED vertex.</p>`,
});

/* ---------- §48 forest formula ---------- */
scene({
  id: "forests", track: "ck", title: "Zimmermann forests", sections: [48],
  summary: "A forest is a set of divergent subgraphs that are pairwise nested or disjoint. Toggle candidates: overlapping selections are rejected, and each legal forest generates its subtraction term ∏(−T<sub>γ</sub>).",
  refs: ["zimmermann1969", "ck2000", "kreimer1999"],
  graphs: true,
  init: () => ({ graph: "sigma2_crossed", chosen: [] }),
  controls: (c) => graphSelect("graph", c.s.graph),
  onSet: (c, key) => { if (key === "graph") c.s.chosen = []; },
  actions: {
    pick: (c, arg) => {
      const i = Number(arg), next = c.s.chosen.includes(i) ? c.s.chosen.filter((x) => x !== i) : [...c.s.chosen, i];
      const chk = HO.checkForest(GR.byId(c.s.graph), next);
      if (chk.ok) { c.s.chosen = next; c.s.reject = null; } else c.s.reject = chk.pair;
    },
  },
  panels: {
    diagram: (c) => {
      const { g, subs } = graphWithSubs(c);
      const boxes = subs.map((s, i) => ({ vertices: s.vertices, edges: s.edges, depth: subs.filter((t) => t !== s && GR.relation(s, t) === "contains").length, cls: c.s.chosen.includes(i) ? "sel" : "", label: `γ${i + 1}`, act: "pick", arg: i, link: `sub${i}` }));
      return { title: "CANDIDATE SUBGRAPHS", sub: "click a box to toggle", body: svg(400, 240, feynman(g, [16, 16, 368, 210], { boxes }), "forest candidates"), foot: c.s.reject ? `<span class="fail">Rejected: γ${c.s.reject[0] + 1} and γ${c.s.reject[1] + 1} overlap.</span>` : `Chosen: {${c.s.chosen.map((i) => `γ${i + 1}`).join(", ") || "∅"}} — a legal forest.` };
    },
    algebra: (c) => {
      const g = GR.byId(c.s.graph), { subgraphs, forests } = HO.forests(g);
      return { title: "ALL FORESTS", sub: `${forests.length} legal`, body: table(["forest", "subtraction term"], forests.map((f) => { const names = f.map((s) => `γ${subgraphs.indexOf(s) + 1}`); return [`{${names.join(", ") || "∅"}}`, f.length ? `${names.map((n) => `(−T<sub>${n}</sub>)`).join("")} φ(Γ)` : "φ(Γ)"]; })) + `<p class="small">Zimmermann: R(Γ) = (1 − T_Γ) ∑_F ∏_{γ∈F}(−T_γ) φ(Γ). In the Hopf algebra the same sum is the convolution γ₋ ⋆ φ.</p>` };
    },
    field: (c) => {
      const { subs } = graphWithSubs(c);
      return { title: "RELATIONS", sub: "nested / disjoint / overlapping", body: table(["", ...subs.map((_, i) => `γ${i + 1}`)], subs.map((s, i) => [`γ${i + 1}`, ...subs.map((t, j) => (i === j ? "—" : GR.relation(s, t)))])) };
    },
    space: () => ({ title: "WHY OVERLAPS ARE EXCLUDED", body: `<p class="small">Two overlapping subdivergences share lines; contracting one destroys the other. A forest only ever contracts subgraphs that can be contracted in some order, from the inside out.</p>` }),
  },
  notes: () => `<p>Forests make subtraction of nested divergences tangible: each forest is one way of contracting compatible subgraphs. The overlapping vertex subgraphs of the crossed self-energy never share a forest, which is why it has three: ∅, {γ₁}, {γ₂}.</p>`,
});

/* ---------- §49 antipode as recursive counterterm ---------- */
scene({
  id: "antipode", track: "ck", title: "Antipode as recursive counterterm", sections: [49],
  summary: "S(Γ) = −Γ − ∑ S(γ)(Γ/γ): the whole divergence, minus the subdivergences, minus what remains overall. The counterterm recursion γ₋(Γ) = −T[φ(Γ) + ∑ γ₋(γ)φ(Γ/γ)] is the same recursion with T inserted.",
  refs: ["ck2000", "kreimer1998", "manchon2008"],
  graphs: true,
  init: () => ({ graph: "sigma3_rainbow", L: 0.5, phase: 0 }),
  controls: (c) => `${graphSelect("graph", c.s.graph)} ${slider("L", "log μ (toy)", -1, 2, 0.01, c.s.L, (v) => v.toFixed(2))} ${stepper("phase", ["whole divergence", "subtract subdivergences", "subtract the remaining overall divergence"], c.s.phase)}`,
  panels: {
    algebra: (c) => {
      const g = GR.byId(c.s.graph), S = HO.antipode(g);
      return { title: "S(Γ) AS A POLYNOMIAL", sub: `${S.size} terms`, body: table(["coefficient", "monomial"], [...S].map(([m, k]) => [k > 0 ? `+${k}` : String(k), esc(monoNames(m))]), [0]) + `<p class="small">Check m(S ⊗ id)ΔΓ = 0: ${HO.antipodeCheck(g).size === 0 ? '<span class="pass">holds</span>' : '<span class="fail">fails</span>'}.</p>` };
    },
    field: (c) => {
      const b = ENG.birkhoffGraph(c.s.graph, c.s.L);
      return { title: "COUNTERTERM RECURSION", sub: "toy Feynman rules", body: table(["subgraph γ", "γ₋(γ)", "γ₋(γ)·φ(Γ/γ)"], b.steps.map((st) => [esc(st.sub.join(" · ")), esc(LS.toText(st.counterterm, { sig: 3 })), esc(LS.toText(LS.truncate(st.value, 0), { sig: 3 }))])) + kv([["R̄(Γ) = φ(Γ) + ∑", esc(LS.toText(LS.truncate(b.bar, 0), { sig: 4 }))], ["γ₋(Γ) = −T R̄(Γ)", esc(LS.toText(b.minus, { sig: 4 }))]]) + `<p class="tiny muted">${TOY_NOTE}</p>` };
    },
    diagram: (c) => {
      const g = GR.byId(c.s.graph), subs = GR.divergentSubgraphs(g), all = GR.internalVertices(g).map((v) => v.id);
      const ph = c.s.phase;
      const boxes = ph === 0 ? [{ vertices: all, edges: [], cls: "sel", label: "Γ: the whole divergence", depth: 2 }] : ph === 1 ? subgraphBoxes(g, subs, { labels: true }).map((b) => ({ ...b, cls: "sel" })) : [{ vertices: all, edges: [], cls: "sel", label: "Γ with subdivergences removed: −T", depth: 2 }];
      const faded = ph === 2 ? new Set(subs.flatMap((s2) => s2.edges)) : null;
      const b = ENG.birkhoffGraph(c.s.graph, c.s.L);
      const caption = ph === 0 ? `φ(Γ) = ${LS.toText(LS.truncate(b.phi, 0), { sig: 3 })}` : ph === 1 ? `+ ∑ γ₋(γ)φ(Γ/γ) over ${b.steps.length} terms` : `γ₋(Γ) = −T[…] = ${LS.toText(b.minus, { sig: 3 })}`;
      return { title: "WHOLE → SUB → OVERALL", sub: ["step 1", "step 2", "step 3"][ph], body: svg(400, 240, feynman(g, [16, 20, 368, 200], { boxes, faded }), "graph"), foot: esc(caption) };
    },
    space: () => ({ title: "TRANSLATION", body: table(["Hopf algebra", "renormalization"], [["S(Γ)", "counterterm without T (formal)"], ["γ₋ = (φ ∘ S) with T inserted", "BPHZ counterterm"], ["m(S ⊗ id)Δ = ε", "the counterterms cancel all divergences"]]) }),
  },
  notes: () => `<p>${formula("S(\\Gamma) = -\\Gamma - \\sum_{\\gamma}S(\\gamma)\\,(\\Gamma/\\gamma),\\qquad \\gamma_-(\\Gamma) = -T\\Big[\\varphi(\\Gamma) + \\sum_\\gamma\\gamma_-(\\gamma)\\varphi(\\Gamma/\\gamma)\\Big]")} The antipode is the counterterm recursion before any pole is projected out; inserting T at each step turns it into Bogoliubov's recursion.</p>`,
});

/* ---------- §50–51 characters and convolution ---------- */
scene({
  id: "characters", track: "ck", title: "Characters and their convolution", sections: [50, 51],
  summary: "A regularized Feynman rule is a character φ: 𝓗 → 𝒜, Γ ↦ φ(Γ)(ε). Characters form a group under (φ ⋆ ψ)(Γ) = m(φ ⊗ ψ)ΔΓ, computed here branch by branch over the coproduct tree.",
  refs: ["ck2000", "manchon2008"],
  graphs: true,
  init: () => ({ graph: "sigma2_rainbow", L: 0.5, psi: "inverse" }),
  controls: (c) => `${graphSelect("graph", c.s.graph)} ${slider("L", "log μ (toy)", -1, 2, 0.01, c.s.L, (v) => v.toFixed(2))} ${seg("psi", [["phi", "φ ⋆ φ"], ["inverse", "φ ⋆ (φ∘S)"], ["minus", "γ₋ ⋆ φ"]], c.s.psi, "convolve")}`,
  panels: {
    field: (c) => {
      const g = GR.byId(c.s.graph), phi = HO.toyCharacter(c.s.L, 6);
      const S = LS.clean(phi.onKey(HO.keyOf(g)));
      return { title: "Γ ↦ φ(Γ)(ε)", sub: "a Laurent series (toy rules)", body: svg(400, 200, laurentLayers(S, { x: 10, y: 10, w: 380, h: 180 }), "character value"), foot: esc(LS.toText(S, { sig: 4 })) };
    },
    algebra: (c) => {
      const g = GR.byId(c.s.graph), phi = HO.toyCharacter(c.s.L, 6);
      const B = HO.birkhoff(phi);
      const [left, right, name] = c.s.psi === "phi" ? [phi, phi, "φ ⋆ φ"] : c.s.psi === "inverse" ? [phi, HO.inverseCharacter(phi), "φ ⋆ (φ ∘ S)"] : [B.minus, phi, "γ₋ ⋆ φ"];
      const cv = HO.convolve(left, right, g);
      const total = LS.clean(cv.total);
      const verdict = c.s.psi === "inverse" ? (total.c.every((x) => Math.abs(x) < 1e-10) ? "= 0 = ε(Γ): φ∘S is the inverse of φ" : "") : c.s.psi === "minus" ? (LS.hasPole(total) ? "" : "no poles: γ₋ ⋆ φ = γ₊ is finite") : "";
      return { title: name, sub: "branch by branch", body: table(["branch", "value"], cv.terms.map((t) => [`${esc(monoNames(t.left))} ⊗ ${esc(monoNames(t.right))}`, esc(LS.toText(LS.clean(LS.truncate(t.value, 1)), { sig: 3 }))])) + `<p class="small"><b>sum:</b> ${esc(LS.toText(LS.truncate(total, 1), { sig: 4 }))} ${verdict}</p>` };
    },
    diagram: (c) => {
      const g = GR.byId(c.s.graph), terms = HO.coproduct(g);
      let s = feynman(g, [140, 0, 120, 60]);
      terms.forEach((t, i) => { const x = 20 + i * (360 / Math.max(1, terms.length - 1)), y = 140; s += path(`M200 62Q${(200 + x) / 2} 90 ${x} ${y - 14}`, "ck", 'fill="none"') + txt(x, y, `${t.kind}`, "xs mono", 'text-anchor="middle"') + txt(x, y + 14, "φ ⊗ ψ", "xs ink2", 'text-anchor="middle"'); });
      return { title: "THE COPRODUCT TREE", sub: "each branch: φ(left)·ψ(right)", body: svg(400, 170, s, "coproduct tree") };
    },
    space: () => ({ title: "THE GROUP", body: formula("(\\varphi\\star\\psi)(\\Gamma) = m(\\varphi\\otimes\\psi)\\Delta\\Gamma,\\quad \\varphi^{\\star-1} = \\varphi\\circ S,\\quad e = \\varepsilon") + `<p class="tiny muted">${TOY_NOTE}</p>` }),
  },
  notes: () => `<p>Characters are algebra maps, so their values on products are products of values. The convolution makes them a group whose unit is the counit and whose inverse is composition with the antipode — checked numerically above (the φ ⋆ (φ∘S) sum vanishes to rounding).</p>`,
});

/* ---------- §52, §54, §55 Birkhoff decomposition ---------- */
scene({
  id: "birkhoff", track: "ck", title: "Birkhoff decomposition", sections: [52, 54, 55],
  summary: "The regularized theory is a loop γ(ε) in the group of characters. Split it: γ = γ₋<sup>−1</sup>γ₊, the negative Laurent part γ₋ (counterterms) and the holomorphic part γ₊, whose value γ₊(0) is the renormalized amplitude.",
  refs: ["ck2000", "ck2001", "cm2008"],
  graphs: true,
  init: () => ({ graph: "sigma2_rainbow", L: 0.5 }),
  controls: (c) => `${graphSelect("graph", c.s.graph, ["sigma1", ...CK_GRAPHS])} ${slider("L", "log μ (toy)", -1, 2, 0.01, c.s.L, (v) => v.toFixed(2))}`,
  present: ["field", "algebra"],
  panels: {
    field: (c) => {
      const b = ENG.birkhoffGraph(c.s.graph, c.s.L);
      const w = 126;
      const s = laurentLayers(b.phi, { x: 4, y: 18, w, h: 150 }) + laurentLayers(b.minus, { x: 137, y: 18, w, h: 150 }) + laurentLayers(b.plus, { x: 270, y: 18, w, h: 150 }) + txt(67, 12, "γ(ε) = φ(Γ)", "xs mono", 'text-anchor="middle" data-link="gamma"') + txt(200, 12, "γ₋ (negative part)", "xs mono", 'text-anchor="middle" data-link="gminus"') + txt(333, 12, "γ₊ (holomorphic)", "xs mono", 'text-anchor="middle" data-link="gplus"');
      return { title: "SPLIT THE LOOP", sub: "regularized amplitude → γ₋, γ₊", body: svg(400, 175, s, "Birkhoff split"), foot: `renormalized value = γ₊(0) = <b>${fmt(b.renormalized, 8)}</b>` };
    },
    algebra: (c) => {
      const b = ENG.birkhoffGraph(c.s.graph, c.s.L);
      return { title: "THE NUMBERS", sub: "toy Feynman rules", body: kv([["φ(Γ)", esc(LS.toText(b.phi, { sig: 4 }))], ["γ₋(Γ)", esc(LS.toText(b.minus, { sig: 4 }))], ["γ₊(Γ)", esc(LS.toText(LS.truncate(b.plus, 2), { sig: 4 }))], ["γ₊(Γ)(0)", fmt(b.renormalized, 10)], ["γ₋<sup>⋆−1</sup> ⋆ γ₊ − φ", Math.max(0, ...b.reconstruction.c.map(Math.abs)) < 1e-10 ? "0 (reconstructs φ)" : esc(LS.toText(b.reconstruction))]]) + `<p class="tiny muted">${TOY_NOTE}</p>` };
    },
    diagram: (c) => {
      const { g, subs } = graphWithSubs(c);
      return { title: "THE GRAPH", sub: esc(g.name), body: svg(400, 200, feynman(g, [16, 16, 368, 175], { boxes: subgraphBoxes(g, subs, { labels: true }) }), "graph") };
    },
    space: (c) => {
      const Ls = Q.linspace(-1, 2, 16), ids = ["sigma1", "sigma2_rainbow", "sigma3_rainbow"];
      return { title: "γ₊(0) IS POLYNOMIAL IN log μ", sub: "ladders: (−L)ⁿ/n!", body: lineChart({ W: 400, H: 200, xr: [-1, 2], yr: [-2.2, 2.2], series: ids.map((id, i) => ({ pts: Ls.map((L) => [L, ENG.birkhoffGraph(id, L).renormalized]), cls: ["qft", "ck", "aqft"][i], label: ["1 loop", "2-loop ladder", "3-loop ladder"][i] })), vlines: [{ x: c.s.L, label: "L" }], xlabel: "L = log μ" }) };
    },
  },
  notes: () => `<p>${formula("\\gamma(\\varepsilon) = \\gamma_-(\\varepsilon)^{-1}\\gamma_+(\\varepsilon)")} Connes and Kreimer identify ${tex("\\gamma_-")} with the counterterms and the value ${tex("\\gamma_+(0)")} with the renormalized theory. Regularized amplitude ├─ negative Laurent part → γ₋ └─ holomorphic part → γ₊; renormalized value = γ₊(0).</p>`,
  md: (c) => ({ title: "Renormalization as Birkhoff decomposition", sections: REP.birkhoffMarkdown(ENG.birkhoffGraph(c.s.graph, c.s.L)), params: { graph: c.s.graph, log_mu: c.s.L } }),
  deckKind: "birkhoff",
});

/* ---------- §53 Riemann sphere ---------- */
scene({
  id: "sphere", track: "ck", title: "Riemann sphere and Riemann–Hilbert", sections: [53],
  summary: "P¹(ℂ) with ε = 0 and a contour around it. γ itself has its pole inside; γ₊ is holomorphic inside the contour, γ₋ outside (with γ₋(∞) = 1). Renormalization ↔ Riemann–Hilbert factorization.",
  refs: ["ck2000", "cm2008"],
  init: () => ({ graph: "pi1", r: 0.3 }),
  anim: ["field"],
  controls: (c) => `${graphSelect("graph", c.s.graph, ["pi1", "sigma1", "sigma2_rainbow", "sigma3_rainbow"])} ${slider("r", "contour radius |ε|", 0.1, 0.8, 0.01, c.s.r, (v) => v.toFixed(2))}`,
  panels: {
    space: (c) => {
      const R = riemannSphere({ cx: 200, cy: 120, R: 100, contour: c.s.r * 0.9 });
      return { title: "P¹(ℂ)", sub: "ε-sphere", body: svg(400, 240, R.s, "Riemann sphere") };
    },
    field: (c) => {
      const series = c.s.graph === "pi1" ? ENG.vacuumPolarization({ mu: muNow() }).series : LS.clean(HO.toyCharacter(0.5, 6).onKey(HO.keyOf(GR.byId(c.s.graph))));
      const loop = HO.loopOnCircle(series, c.s.r, 160);
      const sc = 95 / Math.max(1e-300, ...loop.flatMap((p) => [Math.hypot(...p.gamma), Math.hypot(...p.minus), Math.hypot(...p.plus)]));
      const k = Math.floor((c.t * 30) % 160);
      let s = ln(200, 10, 200, 220, "grid") + ln(10, 115, 390, 115, "grid");
      s += path(pathD(loop.map((p) => [200 + p.gamma[0] * sc, 115 - p.gamma[1] * sc])), "qft", 'fill="none" stroke-width="2" data-link="gamma"') + path(pathD(loop.map((p) => [200 + p.plus[0] * sc, 115 - p.plus[1] * sc])), "ncg", 'fill="none" stroke-width="2" data-link="gplus"') + path(pathD(loop.map((p) => [200 - p.minus[0] * sc, 115 + p.minus[1] * sc])), "ck", 'fill="none" stroke-dasharray="4 3" data-link="gminus"');
      const p = loop[k];
      s += circ(200 + p.gamma[0] * sc, 115 - p.gamma[1] * sc, 4, "fqft");
      s += txt(12, 22, "image of the contour: γ (blue), −γ₋ (orange), γ₊ (green)", "xs ink2");
      return { title: "THE LOOP IN THE VALUE PLANE", sub: c.s.graph === "pi1" ? "QED Π₁" : "toy rules", body: svg(400, 225, s, "loop image") };
    },
    algebra: () => ({ title: "WHERE EACH PIECE LIVES", body: table(["region", "contains", "holomorphic there"], [["C₊ (inside the contour)", "ε = 0 (d = 4)", "γ₊ — evaluate at ε = 0"], ["C₋ (outside)", "ε = ∞", "γ₋ — a polynomial in 1/ε, γ₋(∞) = 1"], ["the contour", "|ε| = r", "γ = γ₋⁻¹γ₊"]]) }),
    diagram: () => ({ title: "THE CORRESPONDENCE", body: formula("\\text{renormalization} \\;\\leftrightarrow\\; \\text{Riemann–Hilbert factorization}") + `<p class="small">Given a loop on a circle with values in a group, factor it into a part holomorphic inside and a part holomorphic outside. For the character group of 𝓗 (pro-unipotent) the factorization exists and is unique once normalized by γ₋(∞) = 1.</p>` }),
  },
  notes: () => `<p>The pole of γ(ε) sits at ε = 0, inside the contour. The factor γ₋ carries it but is holomorphic outside (it is a polynomial in 1/ε); γ₊ is holomorphic inside and its value at ε = 0 is the renormalized amplitude.</p>`,
});

/* ---------- §56–58 RG from factorization, formal diffeomorphisms, QED coupling ---------- */
scene({
  id: "ckrg", track: "ck", title: "Renormalization group from factorization", sections: [56, 57, 58],
  summary: "μ ↦ μe<sup>t</sup> moves the character; γ₋ does not change, γ₊ does, and the β-function is the generator. Renormalization reparametrizes the coupling, g ↦ g + a₂g² + a₃g³ + …: a formal diffeomorphism. For QED, e₀ = μ<sup>ε/2</sup>eZ₁Z₂<sup>−1</sup>Z₃<sup>−1/2</sup>.",
  refs: ["ck2001", "ps", "jostluttinger1950"],
  init: () => ({ t: 4 }),
  anim: [],
  controls: (c) => `${slider("t", "t = log(μ/μ₀)", 0, 30, 0.1, c.s.t, (v) => v.toFixed(1))} <span class="small muted">loop order (status strip) adds coefficients</span>`,
  panels: {
    field: (c) => {
      const n = Math.max(1, G.order) + 1;
      const f = QED.runningSeries(c.s.t, n);
      let s = ln(20, 60, 380, 60, "axis") + ln(20, 150, 380, 150, "axis") + txt(20, 50, "g (before)", "xs ink2") + txt(20, 172, "g + a₂g² + a₃g³ + … (after)", "xs ink2");
      for (let i = 0; i <= 16; i++) { const g0 = (i / 16) * 0.12; const g1 = HO.evalSeries(f, g0); const x0 = 20 + (g0 / 0.13) * 360, x1 = 20 + (g1 / 0.13) * 360; s += ln(x0, 56, x0, 64, "axis") + (x1 < 390 ? ln(x0, 64, x1, 146, "qft", 'opacity="0.6"') + ln(x1, 146, x1, 154, "qft") : ""); }
      return { title: "THE REAL LINE NEAR g = 0, REPARAMETRIZED", sub: `leading log, order ${n - 1}`, body: svg(400, 180, s, "formal diffeomorphism"), foot: `coefficients a_k = b^{k−1}, b = (2/3π)t: ${f.map((x) => fmt(x, 3)).join(", ")}` };
    },
    algebra: (c) => {
      const f = QED.runningSeries(c.s.t / 2, 5), g = QED.runningSeries(c.s.t / 2, 5), fg = HO.composeSeries(f, g, 5), direct = QED.runningSeries(c.s.t, 5);
      return { title: "THE GROUP LAW", sub: "composition of formal series", body: table(["order", "(t/2) ∘ (t/2)", "t directly"], fg.map((x, k) => [`g${Q.sup(k + 1)}`, fmt(x, 6), fmt(direct[k], 6)]), [1, 2]) + `<p class="small">Two RG steps compose into one: the flow is a one-parameter subgroup of the group of formal diffeomorphisms tangent to the identity.</p>` };
    },
    diagram: () => {
      const L = Q.linspace(-1, 2, 13);
      const d = (id, l) => (ENG.birkhoffGraph(id, l + 1e-5).renormalized - ENG.birkhoffGraph(id, l - 1e-5).renormalized) / 2e-5;
      return { title: "μ-DEPENDENCE OF γ₊", sub: "toy ladders", body: lineChart({ W: 400, H: 200, xr: [-1, 2], yr: [-2, 2], series: [{ pts: L.map((l) => [l, d("sigma3_rainbow", l)]), cls: "ck", label: "d/dL γ₊(ℓ₃)" }, { pts: L.map((l) => [l, -ENG.birkhoffGraph("sigma2_rainbow", l).renormalized]), cls: "qft", label: "−γ₊(ℓ₂)", dash: "5 4" }], xlabel: "L = log μ" }), foot: "The two curves coincide: the scale derivative of a renormalized value is fixed by lower orders — the RG, generated by the residue of γ₋." };
    },
    space: () => ({ title: "QED EFFECTIVE COUPLING", sub: "with the Ward simplification", body: formula("e_0 = \\mu^{\\varepsilon/2}e\\,Z_1Z_2^{-1}Z_3^{-1/2} = \\mu^{\\varepsilon/2}e\\,Z_3^{-1/2}") + kv([["Z₃, one loop (computed)", `1 − (2α/3π)/ε = 1 ${fmt(-2 * Q.ALPHA / (3 * PI), 4)}/ε`], ["Z₃^{−1/2}, one loop", `1 + (α/3π)/ε = 1 + ${fmt(Q.ALPHA / (3 * PI), 4)}/ε`], ...(G.order >= 2 ? [["two loops (literature)", "β adds α³/2π² (Jost & Luttinger 1950), fixing Z₃'s α²/ε term"]] : [])]) }),
  },
  notes: () => `<p>Connes and Kreimer derive the renormalization group and the β-function from the Birkhoff decomposition: because γ₋ does not depend on μ, the μ-dependence of γ₊ is generated by a single element, the residue of γ₋. In terms of couplings, renormalization acts by formal diffeomorphisms ${tex("g \\mapsto g + a_2g^2 + a_3g^3 + \\cdots")}; switch the loop order to watch new coefficients appear.</p>`,
});

/* ---------- §59 motivic / Galois preview ---------- */
scene({
  id: "galois", track: "ck", title: "Renormalization and Galois (preview)", sections: [59],
  summary: "Structural idea only: period-like Feynman amplitudes → algebraic structure of graphs → renormalization group → universal / motivic Galois structures (Connes–Marcolli). No claim that all QFT amplitudes are motives of a simple class.",
  refs: ["cm2006", "cm2008"],
  panels: {
    space: () => ({ title: "THE CHAIN", body: `<pre class="small" style="font-family:var(--mono)">period-like Feynman amplitudes\n        ↓\nalgebraic structure of graphs\n        ↓\nrenormalization group\n        ↓\nuniversal / motivic Galois structures</pre>` }),
    field: () => {
      const lg = Q.logGamma1pSeries(5).map((x, k) => x / Math.pow(2, k));
      return { title: "PERIODS IN THE LAURENT COEFFICIENTS", sub: "computed", body: table(["coefficient of εᵏ in log Γ(1 + ε/2)", "value", "closed form"], [[1, fmt(lg[1], 8), "−γ/2"], [2, fmt(lg[2], 8), "ζ(2)/8"], [3, fmt(lg[3], 8), "−ζ(3)/24"], [4, fmt(lg[4], 8), "ζ(4)/64"]], [1]) + `<p class="small">ζ values are periods; they enter every dimensionally regularized amplitude through Γ(ε/2).</p>` };
    },
    algebra: () => ({ title: "WHAT IS (AND IS NOT) CLAIMED", body: `<ul class="small"><li>Connes and Marcolli construct a universal group U* acting on the counterterms of all renormalizable theories, and relate it to a motivic Galois group.</li><li>Not claimed here: that every QFT amplitude is a motive of a simple class.</li></ul>` }),
  },
  notes: () => `<p>An advanced tab: the renormalization group of a theory sits inside a universal "cosmic" Galois group that acts on the geometry of the regularized amplitudes. This view only states the structural idea.</p>`,
});

/* ---------- §112 renormalization tree view ---------- */
const PIPE = ["GRAPH", "DIVERGENT SUBGRAPHS", "COPRODUCT", "COUNTERTERM CHARACTER", "BIRKHOFF FACTORIZATION", "RENORMALIZED VALUE"];
scene({
  id: "pipeline", track: "ck", title: "Renormalization tree view", sections: [112],
  summary: "Every one-loop or multiloop computation gets the same expandable pipeline: GRAPH → DIVERGENT SUBGRAPHS → COPRODUCT → COUNTERTERM CHARACTER → BIRKHOFF FACTORIZATION → RENORMALIZED VALUE.",
  refs: ["ck2000"],
  graphs: true,
  init: () => ({ graph: "sigma3_double", L: 0.5, open: [0, 1, 2, 3, 4, 5] }),
  controls: (c) => `${graphSelect("graph", c.s.graph, ["sigma1", "pi1", "lambda1", ...CK_GRAPHS])} ${slider("L", "log μ (toy)", -1, 2, 0.01, c.s.L, (v) => v.toFixed(2))}`,
  actions: { tog: (c, arg) => { const i = Number(arg); c.s.open = c.s.open.includes(i) ? c.s.open.filter((x) => x !== i) : [...c.s.open, i]; } },
  panels: {
    space: (c) => {
      const g = GR.byId(c.s.graph), b = ENG.birkhoffGraph(c.s.graph, c.s.L), subs = GR.divergentSubgraphs(g);
      const body = [
        svg(300, 120, feynman(g, [4, 4, 292, 112]), "graph"),
        subs.length ? subs.map((s) => esc(`${s.residue.name} {${s.edges.join(",")}}`)).join("<br>") : "none (primitive)",
        b.coproduct.map((t) => esc(`${Array.isArray(t.left) ? t.left.join(" · ") : t.left} ⊗ ${t.right}`)).join("<br>"),
        `γ₋(Γ) = ${esc(LS.toText(b.minus, { sig: 4 }))}`,
        `γ = γ₋⁻¹γ₊, reconstruction error ${Math.max(0, ...b.reconstruction.c.map(Math.abs)).toExponential(1)}`,
        `γ₊(Γ)(0) = <b>${fmt(b.renormalized, 8)}</b> (toy rules)`,
      ];
      return { title: "PIPELINE", sub: "click a stage to expand", body: PIPE.map((p, i) => `<div style="border-left:3px solid var(--ck);padding:.15rem .5rem;margin:.25rem 0"><button class="btn small" type="button" data-act="tog" data-arg="${i}" aria-expanded="${c.s.open.includes(i)}">${p}</button>${c.s.open.includes(i) ? `<div class="small" style="margin:.2rem 0">${body[i]}</div>` : ""}${i < PIPE.length - 1 ? '<div class="muted">↓</div>' : ""}</div>`).join("") };
    },
  },
  onEnter: () => { G.maxPanel = "space"; },
  notes: () => `<p>${TOY_NOTE} The one-loop vacuum polarization runs through the same pipeline with genuine QED numbers in the ${sceneLink("flagship-vp", "flagship")}.</p>`,
});
