// Theorem Learner: proofs from concepts to results against the kit's contract: versioned state, URL and JSON round trips, the Markdown record and the
// beamdswitch deck of every example (scripts/kit/checks.mjs). Generated by scripts/new_visual.py; --update
// rewrites this file. The domain's own tests are in theorem-learner-model.test.mjs.
import { createRequire } from "node:module";
import { kitTests } from "../../../scripts/kit/checks.mjs";

const require = createRequire(import.meta.url);
kitTests({
  slug: "theorem-learner",
  title: "Theorem Learner: proofs from concepts to results",
  model: require("../src/model.js"),
  report: require("../report.js"),
  data: require("../raw.json"),
});
